"""Type stubs for openpyxl.workbook module."""

from openpyxl.worksheet.worksheet import Worksheet

class Workbook:
    @property
    def active(self) -> Worksheet | None: ...
    @property
    def sheetnames(self) -> list[str]: ...
    def __getitem__(self, key: str) -> Worksheet: ...
    def create_sheet(self, title: str | None = ..., index: int | None = ...) -> Worksheet: ...
    def save(self, filename: str) -> None: ...
    def close(self) -> None: ...
