#!/usr/bin/env python3
"""Debug script to see exactly what YAML Python generates"""

import yaml

# Read the DBC file
with open("test_dbc.yaml", 'r') as f:
    dbc_yaml_content = f.read()

# Build command as Python does
command = {
    'command': 'ParseDBC',
    'yaml': dbc_yaml_content
}

# Serialize to YAML
command_yaml = yaml.dump(command)

print("=== YAML GENERATED BY PYTHON ===")
print(command_yaml)
print("=== END ===")

# Try sending it to binary
import subprocess
binary = "./build/aletheia"
result = subprocess.run(
    [binary],
    input=command_yaml.encode('utf-8'),
    capture_output=True,
    timeout=10
)

print("\n=== BINARY RESPONSE ===")
print(result.stdout.decode('utf-8'))
if result.stderr:
    print("\n=== STDERR ===")
    print(result.stderr.decode('utf-8'))
