import Development.Shake
import Development.Shake.FilePath
import System.Directory (createDirectoryLink, removePathForcibly,
                         getHomeDirectory, createDirectoryIfMissing,
                         removeDirectoryRecursive)
import System.Info (os)
import System.Environment (lookupEnv)
import System.Exit (ExitCode(..))
import Data.List (isInfixOf, isPrefixOf, stripPrefix, nub)
import Data.Maybe (listToMaybe)
import Data.Char (isSpace, isDigit)
import Control.Monad (when, unless, forM, forM_)
import GHC.Conc (getNumProcessors)

-- | Trim whitespace from both ends of a string
strip :: String -> String
strip = dropWhile isSpace . reverse . dropWhile isSpace . reverse

-- | Extract the mangled MAlonzo name for a given Agda function from generated Haskell.
-- Looks for pattern: "d_<funcName>_XX ::"
extractMangledName :: String -> String -> Maybe String
extractMangledName funcName content =
    let prefix = "d_" ++ funcName ++ "_"
    in listToMaybe [name | line <- lines content,
                           funcName `isInfixOf` line,
                           "::" `isInfixOf` line,
                           let name = takeWhile (/= ' ') (dropWhile (== ' ') line),
                           prefix `isInfixOf` name]

-- | Extract the function name currently used in the FFI wrapper for a given Agda function.
-- Looks for pattern: "<qualifier>.d_<funcName>_XX" where qualifier is e.g. "AgdaJSON" or "AgdaBin".
extractFFIName :: String -> String -> String -> Maybe String
extractFFIName qualifier funcName content =
    let prefix = "d_" ++ funcName ++ "_"
        qualPrefix = qualifier ++ "." ++ prefix
        qualLen = length qualifier + 1 -- qualifier + "."
    in listToMaybe [cleaned | line <- lines content,
                              qualifier `isInfixOf` line,
                              funcName `isInfixOf` line,
                              let parts = words line,
                              name <- parts,
                              qualPrefix `isInfixOf` name,
                              let cleaned = drop qualLen name,
                              prefix `isInfixOf` cleaned]

-- | Check that the FFI wrapper uses the correct mangled name for a single function.
checkOneFFIName :: String -> String -> String -> String -> Action ()
checkOneFFIName qualifier funcName malonzoContent ffiContent =
    case (extractMangledName funcName malonzoContent, extractFFIName qualifier funcName ffiContent) of
        (Just generatedName, Just ffiName) ->
            when (generatedName /= ffiName) $ do
                putError $ unlines
                    [ ""
                    , "════════════════════════════════════════════════════════════════"
                    , "ERROR: MAlonzo function name mismatch for " ++ funcName ++ "!"
                    , "════════════════════════════════════════════════════════════════"
                    , ""
                    , "  Generated by Agda:  " ++ generatedName
                    , "  Currently in FFI:   " ++ ffiName
                    , ""
                    , "The Agda code structure changed, causing MAlonzo to generate"
                    , "a different mangled name. Update the FFI wrapper to match."
                    , ""
                    , "To fix, run:"
                    , "  sed -i 's/" ++ ffiName ++ "/" ++ generatedName ++ "/g' haskell-shim/src/AletheiaFFI.hs"
                    , ""
                    , "Then rebuild:"
                    , "  cabal run shake -- build"
                    , ""
                    , "════════════════════════════════════════════════════════════════"
                    , ""
                    ]
                error $ "FFI name mismatch for " ++ funcName ++ " - see above for fix instructions"
        (Nothing, _) ->
            putWarn $ "Could not extract mangled name for " ++ funcName ++ " from MAlonzo output"
        (_, Nothing) ->
            putWarn $ "Could not extract " ++ funcName ++ " name from FFI wrapper"

-- | FFI export specification. Single source of truth for both
-- `checkFFINames` (verifies AletheiaFFI.hs matches MAlonzo output) and
-- the `check-ffi-exports`/`regen-ffi-exports` phonies (maintain a
-- checked-in snapshot of mangled names to catch silent drift).
data FFIExport = FFIExport
    { ffiQualifier :: String  -- ^ qualifier used in AletheiaFFI.hs ("AgdaJSON", "AgdaBin", "AgdaState")
    , ffiFuncName  :: String  -- ^ function name as written in Agda
    , ffiModule    :: String  -- ^ MAlonzo output path relative to `build/MAlonzo/Code/`, no .hs suffix
    }

-- | Every FFI-exported Agda definition that the Haskell shim calls.
-- Keep ordered so the regenerated snapshot has a stable diff.
ffiExports :: [FFIExport]
ffiExports =
    [ FFIExport "AgdaJSON"  "processJSONLine"          "Aletheia/Main/JSON"
    , FFIExport "AgdaBin"   "processFrameDirect"       "Aletheia/Main/Binary"
    , FFIExport "AgdaBin"   "processEventDirect"       "Aletheia/Main/Binary"
    , FFIExport "AgdaBin"   "processStartStreamDirect" "Aletheia/Main/Binary"
    , FFIExport "AgdaBin"   "processEndStreamDirect"   "Aletheia/Main/Binary"
    , FFIExport "AgdaBin"   "processFormatDBCDirect"   "Aletheia/Main/Binary"
    , FFIExport "AgdaBin"   "processExtractDirect"     "Aletheia/Main/Binary"
    , FFIExport "AgdaBin"   "processBuildFrameBin"     "Aletheia/Main/Binary"
    , FFIExport "AgdaBin"   "processUpdateFrameBin"    "Aletheia/Main/Binary"
    , FFIExport "AgdaBin"   "processExtractBin"        "Aletheia/Main/Binary"
    , FFIExport "AgdaState" "initialState"             "Aletheia/Protocol/StreamState/Types"
    ]

-- | Load the MAlonzo module contents needed by `ffiExports`, deduplicating
-- across entries that share a module.
loadFFIModuleContents :: Action [(String, String)]
loadFFIModuleContents = do
    let modules = nub (map ffiModule ffiExports)
    liftIO $ forM modules $ \m -> do
        c <- readFile ("build/MAlonzo/Code" </> m <.> "hs")
        return (m, c)

-- | Reverse of MAlonzo's name mangling for entries in the FFI snapshot:
-- strips the "d_" prefix and trailing "_<digits>" suffix. Assumes
-- function names are alphanumeric (no underscores) — true for every
-- entry in `ffiExports`.
inferFuncName :: String -> String
inferFuncName mangled =
    case stripPrefix "d_" mangled of
        Just rest -> reverse (drop 1 (dropWhile isDigit (reverse rest)))
        Nothing   -> mangled

-- | Check that the FFI wrapper uses the correct mangled names for all
-- exported functions listed in `ffiExports`.
checkFFINames :: FilePath -> Action ()
checkFFINames ffiFile = do
    ffiContent <- liftIO $ readFile ffiFile
    moduleContents <- loadFFIModuleContents
    forM_ ffiExports $ \e ->
        case lookup (ffiModule e) moduleContents of
            Just c  -> checkOneFFIName (ffiQualifier e) (ffiFuncName e) c ffiContent
            Nothing -> return ()  -- unreachable: loadFFIModuleContents covers every module

-- | Get GHC runtime .so dependencies for a shared library.
-- Runs ldd and filters for libraries under GHC's lib directory.
getGhcDeps :: FilePath -> Action [FilePath]
getGhcDeps soPath = do
    Stdout ghcLibDir <- cmd "ghc" "--print-libdir"
    let ghcBase = strip ghcLibDir
    Stdout lddOutput <- cmd "ldd" soPath
    let deps = [ resolvedPath
               | line <- lines lddOutput
               , let ws = words line
               , length ws >= 3
               , ws !! 1 == "=>"
               , let resolvedPath = ws !! 2
               , ghcBase `isPrefixOf` resolvedPath
               ]
    return deps

-- | Check that patchelf and Python 3.12+ are available.
checkPrerequisites :: Action ()
checkPrerequisites = do
    Exit patchelfCode <- cmd Shell "command -v patchelf >/dev/null 2>&1"
    case patchelfCode of
        ExitSuccess -> return ()
        ExitFailure _ -> error $ unlines
            [ "patchelf is required for install but not found."
            , "Install it with:"
            , "  Ubuntu/Debian: sudo apt install patchelf"
            , "  macOS:         brew install patchelf"
            , "  Fedora:        sudo dnf install patchelf"
            ]
    Exit pyCode <- cmd Shell "python3 -c 'import sys; sys.exit(0 if sys.version_info >= (3,12) else 1)'"
    case pyCode of
        ExitSuccess -> return ()
        ExitFailure _ -> error "Python 3.12+ is required. Check your python3 version."

main :: IO ()
main = shakeArgs shakeOptions{shakeFiles="build", shakeThreads=0, shakeChange=ChangeModtimeAndDigest} $ do

    phony "build" $ do
        need ["check-stdlib-version"]
        need ["build/libaletheia-ffi.so"]

    phony "build-agda" $ do
        need ["check-stdlib-version"]
        need ["build/MAlonzo/Code/Aletheia/Main.hs"]

    phony "build-haskell" $ do
        need ["check-stdlib-version"]
        need ["build/libaletheia-ffi.so"]

    phony "check-properties" $ do
        putInfo "Type-checking proof-only modules..."
        cores <- liftIO getNumProcessors
        let rtsFlags = ["+RTS", "-N" ++ show cores, "-M4G", "-RTS"]
        let agdaWithRTS mod' = cmd_ (Cwd "src") "agda" (rtsFlags ++ [mod'])
        -- All Properties modules are explicitly invoked below (20 total).
        -- Parser / top-level JSON
        agdaWithRTS "Aletheia/Parser/Properties.agda"
        agdaWithRTS "Aletheia/JSON/Properties.agda"
        -- Protocol
        agdaWithRTS "Aletheia/Protocol/JSON/Properties.agda"
        agdaWithRTS "Aletheia/Protocol/ResponseFormat/Properties.agda"
        agdaWithRTS "Aletheia/Protocol/FrameProcessor/Properties.agda"
        agdaWithRTS "Aletheia/Protocol/Adequacy/WarmCache.agda"
        -- CAN
        agdaWithRTS "Aletheia/CAN/Encoding/Properties.agda"
        agdaWithRTS "Aletheia/CAN/Batch/Properties.agda"
        agdaWithRTS "Aletheia/CAN/DLC/Properties.agda"
        agdaWithRTS "Aletheia/CAN/SignalExtraction/Properties.agda"
        agdaWithRTS "Aletheia/CAN/Endianness/Properties.agda"
        -- DBC
        agdaWithRTS "Aletheia/DBC/Properties.agda"
        agdaWithRTS "Aletheia/DBC/JSONParser/Properties.agda"
        agdaWithRTS "Aletheia/DBC/Validity/Theorem.agda"
        agdaWithRTS "Aletheia/DBC/Formatter/Properties.agda"
        agdaWithRTS "Aletheia/DBC/TextParser/Properties.agda"
        agdaWithRTS "Aletheia/DBC/TextParser/DecRatParse/Properties.agda"
        -- TextParser / TextFormatter aggregator modules.  These are not
        -- proof files themselves, but pulling them into `check-properties`
        -- forces the full TextParser / TextFormatter submodule tree to be
        -- type-checked (they're unreachable from Main.agda's transitive
        -- closure, so the main build walk does not cover them).  B.3.d
        -- Commit 4/6 shipped with a latent `RawSignal : ℚ`-vs-DecRat
        -- mismatch in `TextParser/Topology.agda` precisely because this
        -- guard was missing; Commit 5/6 added it.
        agdaWithRTS "Aletheia/DBC/TextParser.agda"
        agdaWithRTS "Aletheia/DBC/TextFormatter.agda"
        agdaWithRTS "Aletheia/DBC/DecRat/RationalRoundtrip.agda"
        -- LTL
        agdaWithRTS "Aletheia/LTL/JSON/Properties.agda"
        agdaWithRTS "Aletheia/LTL/Adequacy.agda"
        agdaWithRTS "Aletheia/LTL/Adequacy/Pipeline.agda"
        agdaWithRTS "Aletheia/LTL/Coalgebra/Properties.agda"
        agdaWithRTS "Aletheia/LTL/Semantics/MTL.agda"
        agdaWithRTS "Aletheia/LTL/Semantics/Duality.agda"
        agdaWithRTS "Aletheia/LTL/TruthVal/Properties.agda"
        agdaWithRTS "Aletheia/LTL/SignalPredicate/Cache/Properties.agda"
        agdaWithRTS "Aletheia/LTL/SignalPredicate/Evaluation/Properties.agda"
        putInfo "All proof modules type-checked successfully!"

    phony "check-invariants" $ do
        -- Enforce "zero postulates, zero *.Unsafe.agda modules" project-wide.
        -- --safe alone rules out postulates in each module; this rule additionally
        -- forbids any *.Unsafe.agda escape hatch from creeping into the tree.
        -- grep exits 1 when there are no matches (the desired case here), so
        -- we take Exit + Stdout explicitly and ignore the exit code.
        (Exit _, Stdout postulates) <-
            cmd "grep" "-rn" "--include=*.agda" "-E" "^postulate" "src/"
        unless (null (postulates :: String)) $ do
            putError $ "postulate found in Agda source:\n" ++ postulates
            error "check-invariants failed"
        unsafe <- getDirectoryFiles "src" ["//*.Unsafe.agda"]
        unless (null unsafe) $ do
            putError $ "*.Unsafe.agda module(s) found: " ++ show unsafe
            error "check-invariants failed"
        putInfo "Invariants OK: 0 postulates, 0 *.Unsafe.agda modules."

    phony "check-no-properties-in-runtime" $ do
        -- Runtime modules must not import Properties modules; a Properties
        -- import would transitively pull every lemma into MAlonzo output.
        let runtime = [ "src/Aletheia/Main.agda"
                      , "src/Aletheia/Main/JSON.agda"
                      , "src/Aletheia/Main/Binary.agda"
                      , "src/Aletheia/Protocol/Handlers.agda"
                      ]
        -- Wrap the regex in a singleton list so Shake's `cmd` does not split
        -- it on whitespace (the pattern contains a space between "open" and
        -- "import" and would otherwise become multiple argv entries).
        let pat = ["^open import .*\\.Properties\\b|^import .*\\.Properties\\b"]
        (Exit _, Stdout violations) <-
            cmd "grep" ["-nE"] pat runtime
        unless (null (violations :: String)) $ do
            putError $ "Runtime module imports a Properties module:\n" ++ violations
            error "check-no-properties-in-runtime failed"
        putInfo "No Properties imports in runtime modules."

    phony "count-modules" $ do
        agdaFiles <- getDirectoryFiles "src" ["//*.agda"]
        let n = length agdaFiles
        putInfo $ "Agda modules under src/: " ++ show n

    phony "check-fidelity" $ do
        -- MAlonzo constructor-drift smoke test.
        -- The cabal test-suite constructor-fidelity exercises the binary FFI
        -- path end-to-end with hand-rolled constructor calls; if a MAlonzo
        -- mangled name or constructor arity drifts relative to the shim, the
        -- test fails to compile OR segfaults on first frame.
        need ["build/libaletheia-ffi.so"]
        putInfo "Running MAlonzo constructor-fidelity test..."
        cmd_ (Cwd "haskell-shim") "cabal" "test" "constructor-fidelity"
             "--test-show-details=direct"

    phony "check-erasure" $ do
        -- Guard the FFI marshaling assumptions about MAlonzo output shape.
        -- Marshal.hs feeds `unsafeCoerce ()` for the erased proof slot of
        -- CANId constructors; this is safe only while MAlonzo keeps those
        -- slots compiled to `AgdaAny`. Likewise, Timestamp comparisons rely
        -- on the newtype compilation to avoid a hot-path allocation.
        -- If either assumption regresses we want a clear early failure
        -- before ConstructorTest runs.
        need ["build/libaletheia-ffi.so"]
        frame <- liftIO $ readFile "build/MAlonzo/Code/Aletheia/CAN/Frame.hs"
        time  <- liftIO $ readFile "build/MAlonzo/Code/Aletheia/Trace/Time.hs"
        let canIdErasure =
              "C_Standard_12 Integer AgdaAny" `isInfixOf` frame &&
              "C_Extended_16 Integer AgdaAny" `isInfixOf` frame
        unless canIdErasure $
          error $ "check-erasure failed: CAN ID constructors no longer use "
               ++ "AgdaAny for the bound proof. "
               ++ "Marshal.hs mkAgdaCanId assumes the proof slot is erased; "
               ++ "fix Marshal.hs before this regresses end-to-end."
        let tsNewtype = "newtype T_Timestamp_18" `isInfixOf` time
        unless tsNewtype $
          error $ "check-erasure failed: Timestamp is no longer compiled as "
               ++ "a newtype. Trace/Time.agda uses `record ... no-eta-equality` "
               ++ "intentionally so MAlonzo compiles Timestamp comparisons "
               ++ "without a wrapper allocation on the hot path."
        -- Stdlib constructor names used by BinaryOutput.hs.
        -- These are mangled from stdlib's Vec/Sum modules; a stdlib version
        -- bump can silently rename them, breaking pattern matches at runtime.
        vecBase <- liftIO $ readFile "build/MAlonzo/Code/Data/Vec/Base.hs"
        sumBase <- liftIO $ readFile "build/MAlonzo/Code/Data/Sum/Base.hs"
        let vecCtors =
              "C_'91''93'_32"   `isInfixOf` vecBase &&
              "C__'8759'__38"   `isInfixOf` vecBase
        unless vecCtors $
          error $ "check-erasure failed: Vec stdlib constructor names changed. "
               ++ "BinaryOutput.hs pattern-matches on C_'91''93'_32 (nil) and "
               ++ "C__'8759'__38 (cons) — update to match current MAlonzo output."
        let sumCtors =
              "C_inj'8321'_38"  `isInfixOf` sumBase &&
              "C_inj'8322'_42"  `isInfixOf` sumBase
        unless sumCtors $
          error $ "check-erasure failed: Sum stdlib constructor names changed. "
               ++ "BinaryOutput.hs pattern-matches on C_inj'8321'_38 (inj₁) and "
               ++ "C_inj'8322'_42 (inj₂) — update to match current MAlonzo output."
        putInfo "Erasure guards OK: CANId AgdaAny + Timestamp newtype + stdlib constructors."

    phony "check-ffi-exports" $ do
        -- Diff MAlonzo-mangled FFI export names against the checked-in
        -- `haskell-shim/ffi-exports.snapshot`. Guards against silent drift
        -- when Agda definitions are reordered or new definitions are added
        -- above existing exports. Complements `checkFFINames` (run inline
        -- during the Main.hs build rule), which keeps AletheiaFFI.hs in
        -- sync with the mangled names.
        need ["build/MAlonzo/Code/Aletheia/Main.hs"]
        let snapshotFile = "haskell-shim/ffi-exports.snapshot"
        snapshotContent <- liftIO $ readFile snapshotFile
        let parseSnapshotLine l =
                let s = strip l
                in if null s || "#" `isPrefixOf` s
                   then Nothing
                   else case break (== ':') s of
                            (m, ':':n) -> Just (m, n)
                            _          -> Nothing
        let expected =
                [ p
                | Just p <- map parseSnapshotLine (lines snapshotContent)
                ]
        moduleContents <- loadFFIModuleContents
        let failures =
              [ (modName, mangled,
                 extractMangledName (inferFuncName mangled) c)
              | (modName, mangled) <- expected
              , Just c <- [lookup modName moduleContents]
              , not ((mangled ++ " ::") `isInfixOf` c)
              ]
        unless (null failures) $ do
            forM_ failures $ \(m, expected', actual) ->
                putError $ unlines
                    [ ""
                    , "════════════════════════════════════════════════════════════════"
                    , "ERROR: FFI export snapshot drift in " ++ m
                    , "════════════════════════════════════════════════════════════════"
                    , ""
                    , "  Expected (snapshot): " ++ expected'
                    , "  Actual (MAlonzo):    " ++ maybe "<not found>" id actual
                    , ""
                    , "  Snapshot file: " ++ snapshotFile
                    , ""
                    , "  If the drift is intentional, regenerate:"
                    , "    cabal run shake -- regen-ffi-exports"
                    , ""
                    , "════════════════════════════════════════════════════════════════"
                    , ""
                    ]
            error "check-ffi-exports failed: snapshot mismatch"
        putInfo $ "FFI exports match snapshot: "
               ++ show (length expected) ++ " entries."

    phony "regen-ffi-exports" $ do
        -- Rewrite `haskell-shim/ffi-exports.snapshot` from the current
        -- MAlonzo output. Run after an intentional Agda refactor that
        -- changes the mangled numbers.
        need ["build/MAlonzo/Code/Aletheia/Main.hs"]
        moduleContents <- loadFFIModuleContents
        let entries =
              [ ffiModule e ++ ":" ++ n
              | e <- ffiExports
              , Just c <- [lookup (ffiModule e) moduleContents]
              , Just n <- [extractMangledName (ffiFuncName e) c]
              ]
        let missing =
              [ ffiFuncName e ++ " (" ++ ffiModule e ++ ")"
              | e <- ffiExports
              , case lookup (ffiModule e) moduleContents of
                    Just c  -> case extractMangledName (ffiFuncName e) c of
                                   Just _  -> False
                                   Nothing -> True
                    Nothing -> True
              ]
        unless (null missing) $
            error $ "regen-ffi-exports: could not extract mangled name for: "
                 ++ unwords missing
        let header =
                [ "# Frozen list of MAlonzo-mangled FFI export names."
                , "#"
                , "# Purpose: guard against silent drift of the mangled names when Agda"
                , "# definitions are reordered or new definitions are added above existing"
                , "# ones. The build system (Shakefile phony `check-ffi-exports`) diffs the"
                , "# fresh MAlonzo output against this file and fails on mismatch."
                , "#"
                , "# Format: one \"<module>:<mangled-name>\" per non-blank, non-# line."
                , "# Modules are the MAlonzo output files under `build/MAlonzo/Code/`."
                , "#"
                , "# Regenerate after an intentional refactor with:"
                , "#   cabal run shake -- regen-ffi-exports"
                , "#"
                , "# This snapshot is paired with `checkFFINames` in Shakefile.hs, which"
                , "# ensures `haskell-shim/src/AletheiaFFI.hs` calls match these names."
                ]
        liftIO $ writeFile "haskell-shim/ffi-exports.snapshot"
                           (unlines (header ++ entries))
        putInfo $ "Regenerated snapshot with "
               ++ show (length entries) ++ " entries."

    phony "check-stdlib-version" $ do
        -- Verify that the globally installed agda-stdlib matches the
        -- version pinned in `aletheia.agda-lib`. Parses `depend:` from
        -- aletheia.agda-lib, then scans libraries listed in
        -- `$HOME/.agda/libraries` and reads each referenced `.agda-lib`
        -- for its `name:` field. Succeeds iff every required dep matches
        -- at least one installed library. Multi-line `depend:` blocks
        -- (indented continuation lines) are not supported — Aletheia
        -- currently depends only on standard-library on a single line.
        aletheiaLib <- liftIO $ readFile "aletheia.agda-lib"
        let requiredDeps =
              concat [ words rest
                     | l <- lines aletheiaLib
                     , Just rest <- [stripPrefix "depend:" l]
                     ]
        when (null requiredDeps) $
            error "aletheia.agda-lib: no `depend:` line or empty value"
        home <- liftIO getHomeDirectory
        let librariesFile = home </> ".agda" </> "libraries"
        libExists <- doesFileExist librariesFile
        unless libExists $
            error $ "check-stdlib-version failed: "
                 ++ librariesFile ++ " not found. "
                 ++ "Set up Agda libraries config "
                 ++ "(see docs/development/BUILDING.md)"
        libContent <- liftIO $ readFile librariesFile
        let expandHome p = case stripPrefix "~/" p of
                               Just rest -> home </> rest
                               Nothing   -> p
        let paths = [ expandHome s
                    | l <- lines libContent
                    , let s = strip l
                    , not (null s)
                    ]
        names <- forM paths $ \p -> do
            ex <- doesFileExist p
            if ex then do
                c <- liftIO $ readFile p
                let nm = case [ strip w
                              | l <- lines c
                              , Just rest <- [stripPrefix "name:" l]
                              , w <- take 1 (words rest)
                              ] of
                           (n:_) -> n
                           []    -> ""
                return (p, nm)
            else return (p, "")
        let missing =
              [ required
              | required <- requiredDeps
              , null [p | (p, nm) <- names, nm == required]
              ]
        unless (null missing) $ do
            let detail = unlines
                    [ "  " ++ p ++ ": "
                       ++ (if null nm then "<missing or unreadable>" else nm)
                    | (p, nm) <- names
                    ]
            error $ unlines
                [ ""
                , "════════════════════════════════════════════════════════════════"
                , "ERROR: stdlib version mismatch"
                , "════════════════════════════════════════════════════════════════"
                , ""
                , "  aletheia.agda-lib requires: " ++ unwords requiredDeps
                , "  Missing: " ++ unwords missing
                , "  Installed libraries from " ++ librariesFile ++ ":"
                , detail
                , "  Fix: install the missing dependency and register it in "
                , "  " ++ librariesFile
                , ""
                , "════════════════════════════════════════════════════════════════"
                , ""
                ]
        putInfo $ "Stdlib version OK: " ++ unwords requiredDeps

    phony "dist" $ do
        need ["build/libaletheia-ffi.so"]

        let distDir = "dist/aletheia"
        let distLib = distDir </> "lib"
        let distInclude = distDir </> "include"
        let tarball = "dist/aletheia.tar.gz"

        -- Clean previous dist
        liftIO $ removePathForcibly distDir
        liftIO $ removePathForcibly tarball
        liftIO $ createDirectoryIfMissing True distLib
        liftIO $ createDirectoryIfMissing True distInclude

        -- Copy main .so and GHC runtime dependencies
        putInfo "Packaging distribution..."
        cmd_ "cp" "build/libaletheia-ffi.so" distLib
        ghcDeps <- getGhcDeps "build/libaletheia-ffi.so"
        forM_ ghcDeps $ \dep ->
            cmd_ "cp" "-L" dep distLib

        -- Patch RUNPATH so all .so files find each other via $ORIGIN
        Exit patchelfCode <- cmd Shell "command -v patchelf >/dev/null 2>&1"
        case patchelfCode of
            ExitSuccess -> do
                Stdout soFiles <- cmd Shell ("find " ++ distLib ++ " -name '*.so*' -type f")
                forM_ (filter (not . null) (lines soFiles)) $ \f ->
                    cmd_ "patchelf" "--set-rpath" "$ORIGIN" f
            ExitFailure _ ->
                putWarn "patchelf not found — skipping RPATH patching. Set LD_LIBRARY_PATH at runtime."

        -- Strip debug symbols to reduce size (--strip-unneeded, NOT --strip-all:
        -- --strip-all would remove the C export symbols needed by dlsym)
        Exit stripCode <- cmd Shell "command -v strip >/dev/null 2>&1"
        case stripCode of
            ExitSuccess -> do
                putInfo "Stripping debug symbols..."
                Stdout soFiles <- cmd Shell ("find " ++ distLib ++ " -name '*.so*' -type f")
                forM_ (filter (not . null) (lines soFiles)) $ \f ->
                    cmd_ "strip" "--strip-unneeded" f
            ExitFailure _ ->
                putWarn "strip not found — keeping debug symbols."

        -- Copy C header
        cmd_ "cp" "include/aletheia.h" distInclude

        -- Create tarball
        putInfo "Creating tarball..."
        cmd_ "tar" "czf" tarball "-C" "dist" "aletheia/"

        -- Report
        Stdout distSize <- cmd Shell ("du -sh " ++ distDir ++ " | cut -f1")
        Stdout tarSize <- cmd Shell ("du -sh " ++ tarball ++ " | cut -f1")
        let nDeps = length ghcDeps
        putInfo ""
        putInfo "════════════════════════════════════════════════════════════════"
        putInfo "  Distribution packaged"
        putInfo "════════════════════════════════════════════════════════════════"
        putInfo ""
        putInfo $ "  dist/aletheia/           (" ++ strip distSize ++ ")"
        putInfo $ "    lib/libaletheia-ffi.so   (main library)"
        putInfo $ "    lib/libHS*.so            (" ++ show nDeps ++ " GHC runtime deps, RPATH=$ORIGIN)"
        putInfo $ "    include/aletheia.h       (C header)"
        putInfo $ "  dist/aletheia.tar.gz     (" ++ strip tarSize ++ ")"
        putInfo ""
        putInfo "  Usage (no LD_LIBRARY_PATH needed — RPATH handles resolution):"
        putInfo "    gcc -Idist/aletheia/include -Ldist/aletheia/lib \\"
        putInfo "        -Wl,-rpath,'$ORIGIN/../lib' -laletheia-ffi app.c"
        putInfo ""

    phony "install-python" $ do
        need ["build/libaletheia-ffi.so"]
        cmd_ (Cwd "python") "pip3 install -e ."

    phony "docker" $ do
        need ["dist"]
        putInfo "Building Docker runtime image..."
        cmd_ "docker" "build" "-t" "aletheia:latest" "-f" "Dockerfile.runtime" "."
        Stdout imageSize <- cmd Shell "docker images aletheia:latest --format '{{.Size}}'"
        putInfo ""
        putInfo "════════════════════════════════════════════════════════════════"
        putInfo $ "  Docker image: aletheia:latest (" ++ strip imageSize ++ ")"
        putInfo "════════════════════════════════════════════════════════════════"
        putInfo ""
        putInfo "  Run:"
        putInfo "    docker run --rm aletheia:latest python3 -c \\"
        putInfo "      \"from aletheia import AletheiaClient; print('OK')\""
        putInfo ""

    phony "clean" $ do
        putInfo "Cleaning build artifacts..."
        removeFilesAfter "build" ["//*"]
        removeFilesAfter "src" ["//*.agdai"]
        removeFilesAfter "haskell-shim" ["//MAlonzo"]
        cmd_ (Cwd "haskell-shim") "cabal clean"

    "build/MAlonzo/Code/Aletheia/Main.hs" %> \out -> do
        agdaSources <- getDirectoryFiles "src" ["//*.agda"]
        need (map ("src" </>) agdaSources)

        -- Shake's ChangeModtimeAndDigest tracks file content hashes
        -- When any .agda source changes, Shake detects it and re-runs this rule
        -- Agda will then update .agdai files as needed based on source changes
        putInfo "Compiling Agda to Haskell (this may take a few minutes)..."
        cores <- liftIO getNumProcessors
        cmd_ (Cwd "src")
            "agda"
            "+RTS" ("-N" ++ show cores) "-RTS"
            "--compile"
            "--compile-dir=../build"
            "--ghc-dont-call-ghc"
            "Aletheia/Main.agda"

        exists <- doesFileExist out
        if exists
            then do
                putInfo $ "MAlonzo output generated: " ++ out
                -- Check that FFI wrapper uses correct mangled names
                checkFFINames "haskell-shim/src/AletheiaFFI.hs"
            else error $ "Agda compilation failed: " ++ out ++ " not created"

    phony "create-symlink" $ do
        need ["build/MAlonzo/Code/Aletheia/Main.hs"]

        let symlinkPath = "haskell-shim/MAlonzo"
        let target = "../build/MAlonzo"

        -- Remove existing symlink/directory if present
        liftIO $ removePathForcibly symlinkPath

        putInfo $ "Creating symlink: " ++ symlinkPath ++ " -> " ++ target

        if os == "mingw32"
            then cmd_ "cmd" "/c" "mklink /D" symlinkPath target
            else liftIO $ createDirectoryLink target symlinkPath

    "build/libaletheia-ffi.so" %> \out -> do
        -- Depend on all MAlonzo generated Haskell files
        -- This ensures Shake detects any changes from Agda compilation
        malonzoFiles <- getDirectoryFiles "build" ["MAlonzo//**/*.hs"]
        need (map ("build" </>) malonzoFiles)

        need ["create-symlink"]  -- Depend on phony target, not directory
        need [ "haskell-shim/src/AletheiaFFI.hs"
             , "haskell-shim/src/AletheiaFFI/Marshal.hs"
             , "haskell-shim/src/AletheiaFFI/BinaryOutput.hs"
             , "haskell-shim/test/ConstructorTest.hs"
             , "haskell-shim/aletheia.cabal"
             ]

        -- Force Cabal to rebuild when MAlonzo files change
        -- Touch AletheiaFFI.hs to invalidate Cabal's cache
        putInfo "Invalidating Cabal cache (touch AletheiaFFI.hs)..."
        cmd_ "touch" "haskell-shim/src/AletheiaFFI.hs"

        -- Delete intermediate build artifacts to force relink
        putInfo "Cleaning Cabal build artifacts..."
        Stdout ghcVer <- cmd "ghc" "--numeric-version"
        let ghcTag = "ghc-" ++ strip ghcVer
        cmd_ (Cwd "haskell-shim") Shell $ "rm -rf dist-newstyle/build/*/" ++ ghcTag ++ "/aletheia-*/f/aletheia-ffi"

        putInfo "Building FFI shared library..."
        cmd_ (Cwd "haskell-shim") "cabal" "build" "-j" "aletheia-ffi"

        -- Find and copy the built .so file
        Stdout soPath <- cmd (Cwd "haskell-shim") Shell
            "find dist-newstyle -name 'libaletheia-ffi.so' -type f | head -1"
        let trimmedPath = strip soPath
        if null trimmedPath
            then error "Could not find libaletheia-ffi.so in dist-newstyle"
            else do
                cmd_ (Cwd "haskell-shim") "cp" trimmedPath ("../" ++ out)
                putInfo $ "Shared library created: " ++ out

    -- =========================================================================
    -- Install / Uninstall targets
    -- =========================================================================

    phony "install" $ do
        need ["build/libaletheia-ffi.so"]

        -- Read PREFIX (default: ~/.local)
        home <- liftIO getHomeDirectory
        prefixEnv <- liftIO $ lookupEnv "PREFIX"
        let prefix = maybe (home </> ".local") id prefixEnv
        configShellEnv <- liftIO $ lookupEnv "CONFIGURE_SHELL"
        let configShell = configShellEnv == Just "1"

        -- Check prerequisites
        checkPrerequisites

        let libDir     = prefix </> "lib" </> "aletheia"
        let docDir     = prefix </> "share" </> "doc" </> "aletheia"
        let exampleDir = prefix </> "share" </> "aletheia" </> "examples"
        let venvDir    = libDir </> "venv"
        let venvPython = venvDir </> "bin" </> "python3"
        let venvPip    = venvDir </> "bin" </> "pip"

        -- Create directory tree
        putInfo $ "Installing to " ++ prefix ++ " ..."
        liftIO $ createDirectoryIfMissing True libDir
        liftIO $ createDirectoryIfMissing True docDir
        liftIO $ createDirectoryIfMissing True exampleDir

        -- Copy main shared library
        putInfo "Copying shared library..."
        cmd_ "cp" "build/libaletheia-ffi.so" libDir

        -- Bundle GHC runtime dependencies (only if not standalone)
        ghcDeps <- getGhcDeps "build/libaletheia-ffi.so"
        if null ghcDeps
            then putInfo "Standalone .so detected — no GHC libraries to bundle."
            else do
                putInfo "Bundling GHC runtime libraries..."
                forM_ ghcDeps $ \dep ->
                    cmd_ "cp" "-L" dep libDir
                -- Patch RUNPATH on all .so files so they find each other via $ORIGIN
                putInfo "Patching RUNPATH on shared libraries..."
                Stdout soFiles <- cmd Shell ("find " ++ libDir ++ " -name '*.so*' -type f")
                forM_ (filter (not . null) (lines soFiles)) $ \f ->
                    cmd_ "patchelf" "--set-rpath" "$ORIGIN" f

        -- Copy C header
        let includeDir = prefix </> "include" </> "aletheia"
        liftIO $ createDirectoryIfMissing True includeDir
        putInfo "Copying C header..."
        cmd_ "cp" "include/aletheia.h" includeDir

        -- Create Python venv
        putInfo "Creating Python virtual environment..."
        cmd_ "python3" "-m" "venv" venvDir
        cmd_ venvPip "install" "--upgrade" "pip" "setuptools" "wheel"

        -- Install aletheia Python package (non-editable)
        putInfo "Installing aletheia Python package..."
        cmd_ venvPip "install" "./python"

        -- Find site-packages and write _install_config.py
        Stdout sitePackages <- cmd venvPython "-c"
            "import site; print(site.getsitepackages()[0])"
        let siteDir = strip sitePackages
        let configFile = siteDir </> "aletheia" </> "_install_config.py"
        let soAbsPath = libDir </> "libaletheia-ffi.so"
        putInfo $ "Writing install config: " ++ configFile
        liftIO $ writeFile configFile $
            "from pathlib import Path\n\nLIBRARY_PATH: Path = Path(" ++ show soAbsPath ++ ")\n"

        -- Copy documentation
        putInfo "Copying documentation..."
        cmd_ Shell ("cp -r docs/* " ++ docDir ++ "/")
        -- Copy root doc files that exist
        forM_ ["README.md", "CONTRIBUTING.md", "LICENSE.md", "LICENSE"] $ \f -> do
            rootDocExists <- doesFileExist f
            when rootDocExists $ cmd_ "cp" f docDir

        -- Copy examples
        putInfo "Copying examples..."
        examplesExist <- doesDirectoryExist "examples"
        when examplesExist $ do
            cmd_ Shell ("cp -r examples/* " ++ exampleDir ++ "/")
            cmd_ Shell ("find " ++ exampleDir ++ " -name '__pycache__' -type d -exec rm -rf {} + 2>/dev/null || true")

        -- Write manifest for uninstall
        let manifestFile = libDir </> "manifest.txt"
        liftIO $ writeFile manifestFile $ unlines
            [ prefix </> "lib" </> "aletheia"
            , prefix </> "share" </> "doc" </> "aletheia"
            , prefix </> "share" </> "aletheia"
            ]

        -- Optionally configure shell aliases
        when configShell $ do
            putInfo "Configuring shell aliases..."
            let venvActivate     = venvDir </> "bin" </> "activate"
            let venvActivateFish = venvDir </> "bin" </> "activate.fish"
            let marker = "# Added by aletheia install"

            -- bash
            let bashrc = home </> ".bashrc"
            bashExists <- doesFileExist bashrc
            when bashExists $ do
                Stdout bashContent <- cmd Shell ("cat " ++ bashrc)
                unless (marker `isInfixOf` bashContent) $ do
                    liftIO $ appendFile bashrc $ unlines
                        [ "", marker
                        , "alias aletheia-env='source " ++ venvActivate ++ "'"
                        ]
                    putInfo $ "  Added alias to " ++ bashrc

            -- zsh
            let zshrc = home </> ".zshrc"
            zshExists <- doesFileExist zshrc
            when zshExists $ do
                Stdout zshContent <- cmd Shell ("cat " ++ zshrc)
                unless (marker `isInfixOf` zshContent) $ do
                    liftIO $ appendFile zshrc $ unlines
                        [ "", marker
                        , "alias aletheia-env='source " ++ venvActivate ++ "'"
                        ]
                    putInfo $ "  Added alias to " ++ zshrc

            -- fish
            let fishConfig = home </> ".config" </> "fish" </> "config.fish"
            fishExists <- doesFileExist fishConfig
            when fishExists $ do
                Stdout fishContent <- cmd Shell ("cat " ++ fishConfig)
                unless (marker `isInfixOf` fishContent) $ do
                    liftIO $ appendFile fishConfig $ unlines
                        [ "", marker
                        , "alias aletheia-env 'source " ++ venvActivateFish ++ "'"
                        ]
                    putInfo $ "  Added alias to " ++ fishConfig

        -- Success banner
        putInfo ""
        putInfo "════════════════════════════════════════════════════════════════"
        putInfo "  Aletheia installed successfully!"
        putInfo "════════════════════════════════════════════════════════════════"
        putInfo ""
        putInfo $ "  Location: " ++ prefix
        putInfo ""
        putInfo "  Activate the environment:"
        putInfo $ "    bash/zsh: source " ++ venvDir </> "bin" </> "activate"
        putInfo $ "    fish:     source " ++ venvDir </> "bin" </> "activate.fish"
        putInfo ""
        putInfo "  Then use:"
        putInfo "    python3 -c \"from aletheia import AletheiaClient; print('OK')\""
        putInfo ""
        putInfo "  Uninstall:"
        putInfo $ "    " ++ (if prefixEnv /= Nothing then "PREFIX=" ++ prefix ++ " " else "")
              ++ "cabal run shake -- uninstall"
        putInfo ""

    phony "uninstall" $ do
        -- Read PREFIX (default: ~/.local)
        home <- liftIO getHomeDirectory
        prefixEnv <- liftIO $ lookupEnv "PREFIX"
        let prefix = maybe (home </> ".local") id prefixEnv
        let manifestFile = prefix </> "lib" </> "aletheia" </> "manifest.txt"

        manifestExists <- doesFileExist manifestFile
        if manifestExists
            then do
                manifestContent <- liftIO $ readFile manifestFile
                let dirs = filter (not . null) (lines manifestContent)
                forM_ dirs $ \dir -> do
                    dirExists <- doesDirectoryExist dir
                    when dirExists $ do
                        putInfo $ "Removing " ++ dir ++ " ..."
                        liftIO $ removeDirectoryRecursive dir
                -- Clean up empty parent dirs
                let shareAletheiaDir = prefix </> "share" </> "aletheia"
                shareExists <- doesDirectoryExist shareAletheiaDir
                when shareExists $
                    liftIO $ removeDirectoryRecursive shareAletheiaDir
                putInfo ""
                putInfo "Aletheia uninstalled successfully."
                putInfo ""
            else do
                putInfo $ "No manifest found at " ++ manifestFile
                putInfo "Nothing to uninstall."
