import Development.Shake
import Development.Shake.FilePath
import System.Directory (createDirectoryLink, removePathForcibly,
                         getHomeDirectory, createDirectoryIfMissing,
                         removeDirectoryRecursive,
                         getCurrentDirectory)
import qualified System.Directory as SysDir
import System.Info (os)
import System.Environment (lookupEnv)
import System.Exit (ExitCode(..))
import Data.List (isInfixOf, isPrefixOf, stripPrefix, nub)
import Data.Maybe (listToMaybe)
import Data.Char (isSpace, isDigit)
import Control.Monad (when, unless, forM, forM_)
import GHC.Conc (getNumProcessors)

-- | Trim whitespace from both ends of a string
strip :: String -> String
strip = dropWhile isSpace . reverse . dropWhile isSpace . reverse

-- | Extract the mangled MAlonzo name for a given Agda function from generated Haskell.
-- Looks for pattern: "d_<funcName>_XX ::"
extractMangledName :: String -> String -> Maybe String
extractMangledName funcName content =
    let prefix = "d_" ++ funcName ++ "_"
    in listToMaybe [name | line <- lines content,
                           funcName `isInfixOf` line,
                           "::" `isInfixOf` line,
                           let name = takeWhile (/= ' ') (dropWhile (== ' ') line),
                           prefix `isInfixOf` name]

-- | Extract the function name currently used in the FFI wrapper for a given Agda function.
-- Looks for pattern: "<qualifier>.d_<funcName>_XX" where qualifier is e.g. "AgdaJSON" or "AgdaBin".
extractFFIName :: String -> String -> String -> Maybe String
extractFFIName qualifier funcName content =
    let prefix = "d_" ++ funcName ++ "_"
        qualPrefix = qualifier ++ "." ++ prefix
        qualLen = length qualifier + 1 -- qualifier + "."
    in listToMaybe [cleaned | line <- lines content,
                              qualifier `isInfixOf` line,
                              funcName `isInfixOf` line,
                              let parts = words line,
                              name <- parts,
                              qualPrefix `isInfixOf` name,
                              let cleaned = drop qualLen name,
                              prefix `isInfixOf` cleaned]

-- | Check that the FFI wrapper uses the correct mangled name for a single function.
checkOneFFIName :: String -> String -> String -> String -> Action ()
checkOneFFIName qualifier funcName malonzoContent ffiContent =
    case (extractMangledName funcName malonzoContent, extractFFIName qualifier funcName ffiContent) of
        (Just generatedName, Just ffiName) ->
            when (generatedName /= ffiName) $ do
                putError $ unlines
                    [ ""
                    , "════════════════════════════════════════════════════════════════"
                    , "ERROR: MAlonzo function name mismatch for " ++ funcName ++ "!"
                    , "════════════════════════════════════════════════════════════════"
                    , ""
                    , "  Generated by Agda:  " ++ generatedName
                    , "  Currently in FFI:   " ++ ffiName
                    , ""
                    , "The Agda code structure changed, causing MAlonzo to generate"
                    , "a different mangled name. Update the FFI wrapper to match."
                    , ""
                    , "To fix, run:"
                    , "  sed -i 's/" ++ ffiName ++ "/" ++ generatedName ++ "/g' haskell-shim/src/AletheiaFFI.hs"
                    , ""
                    , "Then rebuild:"
                    , "  cabal run shake -- build"
                    , ""
                    , "════════════════════════════════════════════════════════════════"
                    , ""
                    ]
                error $ "FFI name mismatch for " ++ funcName ++ " - see above for fix instructions"
        (Nothing, _) ->
            putWarn $ "Could not extract mangled name for " ++ funcName ++ " from MAlonzo output"
        (_, Nothing) ->
            putWarn $ "Could not extract " ++ funcName ++ " name from FFI wrapper"

-- | FFI export specification. Single source of truth for both
-- `checkFFINames` (verifies AletheiaFFI.hs matches MAlonzo output) and
-- the `check-ffi-exports`/`regen-ffi-exports` phonies (maintain a
-- checked-in snapshot of mangled names to catch silent drift).
data FFIExport = FFIExport
    { ffiQualifier :: String  -- ^ qualifier used in AletheiaFFI.hs ("AgdaJSON", "AgdaBin", "AgdaState")
    , ffiFuncName  :: String  -- ^ function name as written in Agda
    , ffiModule    :: String  -- ^ MAlonzo output path relative to `build/MAlonzo/Code/`, no .hs suffix
    }

-- | Every FFI-exported Agda definition that the Haskell shim calls.
-- Keep ordered so the regenerated snapshot has a stable diff.
ffiExports :: [FFIExport]
ffiExports =
    [ FFIExport "AgdaJSON"  "processJSONLine"          "Aletheia/Main/JSON"
    , FFIExport "AgdaBin"   "processFrameDirect"       "Aletheia/Main/Binary"
    , FFIExport "AgdaBin"   "processEventDirect"       "Aletheia/Main/Binary"
    , FFIExport "AgdaBin"   "processStartStreamDirect" "Aletheia/Main/Binary"
    , FFIExport "AgdaBin"   "processEndStreamDirect"   "Aletheia/Main/Binary"
    , FFIExport "AgdaBin"   "processFormatDBCDirect"   "Aletheia/Main/Binary"
    , FFIExport "AgdaBin"   "processExtractDirect"     "Aletheia/Main/Binary"
    , FFIExport "AgdaBin"   "processBuildFrameBin"     "Aletheia/Main/Binary"
    , FFIExport "AgdaBin"   "processUpdateFrameBin"    "Aletheia/Main/Binary"
    , FFIExport "AgdaBin"   "processExtractBin"        "Aletheia/Main/Binary"
    , FFIExport "AgdaState" "initialState"             "Aletheia/Protocol/StreamState/Types"
    , FFIExport "AgdaRR"    "formatRational"           "Aletheia/DBC/RationalRenderer"
    ]

-- | Load the MAlonzo module contents needed by `ffiExports`, deduplicating
-- across entries that share a module.
loadFFIModuleContents :: Action [(String, String)]
loadFFIModuleContents = do
    let modules = nub (map ffiModule ffiExports)
    liftIO $ forM modules $ \m -> do
        c <- readFile ("build/MAlonzo/Code" </> m <.> "hs")
        return (m, c)

-- | Human-readable label for FFI snapshot entry kinds (`F`/`C`/`T`).
-- Used in `check-ffi-exports` diagnostics — keeps the error message
-- self-explanatory ("function snapshot drift" vs "constructor …").
kindLabel :: String -> String
kindLabel "F" = "function"
kindLabel "C" = "constructor"
kindLabel "T" = "type"
kindLabel k   = "entry (" ++ k ++ ")"

-- | Reverse of MAlonzo's name mangling for entries in the FFI snapshot:
-- strips the "d_" prefix and trailing "_<digits>" suffix. Assumes
-- function names are alphanumeric (no underscores) — true for every
-- entry in `ffiExports`.
inferFuncName :: String -> String
inferFuncName mangled =
    case stripPrefix "d_" mangled of
        Just rest -> reverse (drop 1 (dropWhile isDigit (reverse rest)))
        Nothing   -> mangled

-- | Check that the FFI wrapper uses the correct mangled names for all
-- exported functions listed in `ffiExports`.
checkFFINames :: FilePath -> Action ()
checkFFINames ffiFile = do
    ffiContent <- liftIO $ readFile ffiFile
    moduleContents <- loadFFIModuleContents
    forM_ ffiExports $ \e ->
        case lookup (ffiModule e) moduleContents of
            Just c  -> checkOneFFIName (ffiQualifier e) (ffiFuncName e) c ffiContent
            Nothing -> return ()  -- unreachable: loadFFIModuleContents covers every module

-- | Parse the digest-pinned base image from Dockerfile.runtime.
-- Returns the value after `FROM ` up to end-of-line (e.g.
-- `python:3.13-slim@sha256:...`).  Falls back to "unknown" if no
-- `FROM` line is found.
parseFromBase :: String -> String
parseFromBase dockerfile =
    case [ rest | l <- lines dockerfile
                , Just rest <- [stripPrefix "FROM " l]
                ]
      of (x:_) -> strip x
         []    -> "unknown"

-- | Parse the pinned libgmp10 version from Dockerfile.runtime.
-- Looks for the `libgmp10=<version>` token inside an `apt-get install`
-- line and returns just the version.  Falls back to "unknown".
parseLibgmpVersion :: String -> String
parseLibgmpVersion dockerfile =
    case [ ver | tok <- words dockerfile
               , Just rest <- [stripPrefix "libgmp10=" tok]
               , let ver = takeWhile (\c -> c /= ' ' && c /= '\\' && c /= '\n') rest
               , not (null ver)
               ]
      of (x:_) -> x
         []    -> "unknown"

-- | Get GHC runtime .so dependencies for a shared library.
-- Runs ldd and filters for libraries under GHC's lib directory.
getGhcDeps :: FilePath -> Action [FilePath]
getGhcDeps soPath = do
    Stdout ghcLibDir <- cmd "ghc" "--print-libdir"
    let ghcBase = strip ghcLibDir
    Stdout lddOutput <- cmd "ldd" soPath
    let deps = [ resolvedPath
               | line <- lines lddOutput
               , let ws = words line
               , length ws >= 3
               , ws !! 1 == "=>"
               , let resolvedPath = ws !! 2
               , ghcBase `isPrefixOf` resolvedPath
               ]
    return deps

-- | Compute SHA-256 of a file via the system sha256sum binary.
-- Returns the hex digest only (no path/whitespace).
sha256file :: FilePath -> Action String
sha256file p = do
    Stdout out <- cmd "sha256sum" p
    return $ takeWhile (/= ' ') out

-- | Check that patchelf and Python 3.12+ are available.
checkPrerequisites :: Action ()
checkPrerequisites = do
    Exit patchelfCode <- cmd Shell "command -v patchelf >/dev/null 2>&1"
    case patchelfCode of
        ExitSuccess -> return ()
        ExitFailure _ -> error $ unlines
            [ "patchelf is required for install but not found."
            , "Install it with:"
            , "  Ubuntu/Debian: sudo apt install patchelf"
            , "  macOS:         brew install patchelf"
            , "  Fedora:        sudo dnf install patchelf"
            ]
    Exit pyCode <- cmd Shell "python3 -c 'import sys; sys.exit(0 if sys.version_info >= (3,12) else 1)'"
    case pyCode of
        ExitSuccess -> return ()
        ExitFailure _ -> error "Python 3.12+ is required. Check your python3 version."

main :: IO ()
main = shakeArgs shakeOptions{shakeFiles="build", shakeThreads=0, shakeChange=ChangeModtimeAndDigest} $ do

    phony "build" $ do
        need ["check-stdlib-version"]
        need ["build/libaletheia-ffi.so"]

    phony "build-agda" $ do
        need ["check-stdlib-version"]
        need ["build/MAlonzo/Code/Aletheia/Main.hs"]

    phony "build-haskell" $ do
        need ["check-stdlib-version"]
        need ["build/libaletheia-ffi.so"]

    phony "check-properties" $ do
        putInfo "Type-checking proof-only modules..."
        cores <- liftIO getNumProcessors
        let rtsFlags = ["+RTS", "-N" ++ show cores, "-M16G", "-RTS"]
        let agdaWithRTS mod' = cmd_ (Cwd "src") "agda" (rtsFlags ++ [mod'])
        -- All Properties modules are explicitly invoked below (20 total).
        -- Parser / top-level JSON
        agdaWithRTS "Aletheia/Parser/Properties.agda"
        agdaWithRTS "Aletheia/JSON/Properties.agda"
        -- Protocol
        agdaWithRTS "Aletheia/Protocol/JSON/Properties.agda"
        agdaWithRTS "Aletheia/Protocol/ResponseFormat/Properties.agda"
        agdaWithRTS "Aletheia/Protocol/FrameProcessor/Properties.agda"
        agdaWithRTS "Aletheia/Protocol/Adequacy/WarmCache.agda"
        -- CAN
        agdaWithRTS "Aletheia/CAN/Encoding/Properties.agda"
        agdaWithRTS "Aletheia/CAN/Batch/Properties.agda"
        agdaWithRTS "Aletheia/CAN/DLC/Properties.agda"
        agdaWithRTS "Aletheia/CAN/SignalExtraction/Properties.agda"
        agdaWithRTS "Aletheia/CAN/Endianness/Properties.agda"
        -- DBC
        agdaWithRTS "Aletheia/DBC/Properties.agda"
        agdaWithRTS "Aletheia/DBC/JSONParser/Properties.agda"
        agdaWithRTS "Aletheia/DBC/Validity/Theorem.agda"
        agdaWithRTS "Aletheia/DBC/Formatter/Properties.agda"
        agdaWithRTS "Aletheia/DBC/Formatter/Bounded.agda"
        agdaWithRTS "Aletheia/DBC/TextParser/Properties.agda"
        agdaWithRTS "Aletheia/DBC/TextParser/DecRatParse/Properties.agda"
        -- R20 cluster Y stage 2: cross-binding-identical Rational pretty-
        -- printer's correctness properties.  `RationalRenderer` itself
        -- IS reachable from Main.agda (the FFI shim calls it), but
        -- `RationalRenderer.Properties` is a proof-only module unreached
        -- by the runtime walk.  Walk-root rationale per
        -- `feedback_check_properties_aggregator_walks.md`.
        agdaWithRTS "Aletheia/DBC/RationalRenderer/Properties.agda"
        -- TextParser / TextFormatter aggregator modules.  These are not
        -- proof files themselves, but pulling them into `check-properties`
        -- forces the full TextParser / TextFormatter submodule tree to be
        -- type-checked (they're unreachable from Main.agda's transitive
        -- closure, so the main build walk does not cover them).  B.3.d
        -- Commit 4/6 shipped with a latent `RawSignal : ℚ`-vs-DecRat
        -- mismatch in `TextParser/Topology.agda` precisely because this
        -- guard was missing; Commit 5/6 added it.
        agdaWithRTS "Aletheia/DBC/TextParser.agda"
        agdaWithRTS "Aletheia/DBC/TextFormatter.agda"
        agdaWithRTS "Aletheia/DBC/DecRat/RationalRoundtrip.agda"
        -- B.3.d Layer 3 Commit 3d.1: WellFormedText predicates.  Currently
        -- unimported (3d.2+ per-construct proofs will pull it in); explicit
        -- walk root keeps it from bit-rotting per
        -- `feedback_check_properties_aggregator_walks.md`.  Remove this
        -- root once a downstream proof imports it.
        agdaWithRTS "Aletheia/DBC/Formatter/WellFormedText.agda"
        -- Track E.8: `ValueDescResolves` predicate (Bool `resolvesᵇ` +
        -- `Set` lift).  Currently unimported pending the A/B/C wiring
        -- decision (E.11 validator API contract).  Remove this root once
        -- E.11 wires it via the validator.
        agdaWithRTS "Aletheia/DBC/Formatter/WellFormedText/ValueDescResolves.agda"
        -- B.3.d Layer 3 3d.5.a: Format DSL framework core.  Currently
        -- unimported (3d.5.b will use it for parseValueTable; 3d.5.d will
        -- migrate 3a–3d.3 proofs onto it); same walk-root rationale as
        -- WellFormedText above.
        agdaWithRTS "Aletheia/DBC/TextParser/Format.agda"
        -- R22 continuation of R21 AGDA-D-15.1 closure: the L1-L9 regression
        -- test bank that drift-checks the universal `roundtrip` was extracted
        -- from `Format.agda` (to bring it under the 800-LOC trigger).  Walk
        -- root keeps the drift-check active since nothing else imports it.
        agdaWithRTS "Aletheia/DBC/TextParser/Format/RegressionTests.agda"
        -- B.3.d Layer 3 3d.5.b: Format DSL gate-target — parseValueTable
        -- expressed in the DSL (88 code-LOC vs the 613-LOC existing
        -- proof, 86% reduction).  Same walk-root rationale; 3d.5.d
        -- migration may consolidate by replacing the existing parser.
        agdaWithRTS "Aletheia/DBC/TextParser/Format/ValueTable.agda"
        -- B.3.d Layer 3 3d.5.c-γ.1: canonical receivers refinement type
        -- (record + Bool predicate + smart constructor) — lives upstream
        -- of `Types.agda` so the AST can reference it in γ.2.  Walk-root
        -- because Main.agda doesn't reach it until γ.2 wires the AST.
        agdaWithRTS "Aletheia/DBC/CanonicalReceivers.agda"
        -- B.3.d Layer 3 3d.5.c-γ.1: DSL-side canonical receivers format.
        -- Refines `List Identifier` to a record carrier excluding the
        -- singleton-Vector__XXX placeholder; γ.2 retypes
        -- `DBCSignal.receivers` to use it.  Walk-root for the same
        -- reason as Format itself — γ.2 wires it in.
        agdaWithRTS "Aletheia/DBC/TextParser/Format/Receivers.agda"
        -- B.3.d Layer 3 3d.5.c-γ.3: DSL-based receivers roundtrip
        -- (86 strict-code-LOC vs the existing 417 strict-code-LOC in
        -- Properties/Topology/Receivers, ≈80% reduction).  Body is one
        -- `roundtrip canonicalReceiversFmt` call backed by an EmitsOK
        -- builder from the SuffixStops precondition.  δ migrates 3d.3
        -- dispatchers to consume this in place of the existing
        -- `parseReceiverList∘strip-roundtrip` API.
        agdaWithRTS "Aletheia/DBC/TextParser/Format/Receivers/Roundtrip.agda"
        -- B.3.d Layer 3 3d.5.c-η: DSL-side `signalLineFmt` and its
        -- universal roundtrip.  Both are reachable from Main.agda via
        -- `Topology.SignalLine` (production parser uses
        -- `parse signalLineFmt`) and `Properties.Topology.Signal` (slim
        -- dispatchers use `signalLine-roundtrip`); the explicit walk
        -- roots match the pattern set for `Format.Receivers` and guard
        -- against bit-rot if future migration ever detaches them from
        -- the main walk (per `feedback_check_properties_aggregator_
        -- walks.md`).
        agdaWithRTS "Aletheia/DBC/TextParser/Format/SignalLine.agda"
        agdaWithRTS "Aletheia/DBC/TextParser/Format/SignalLine/Roundtrip.agda"
        -- B.3.d Layer 3 3d.5.d: DSL-side `nodeListFmt` (BU_ node-list line)
        -- and the slim `parseBU-roundtrip` derived via the universal
        -- roundtrip.  Same defensive walk-root pattern as the other
        -- Format/* modules above.
        agdaWithRTS "Aletheia/DBC/TextParser/Format/Nodes.agda"
        -- B.3.d Layer 3 3d.5.d-3a: DSL-side preamble formats (VERSION,
        -- BS_, NS_) and the slim `parseVersion-roundtrip` /
        -- `parseBitTiming-roundtrip` / `parseNamespace-roundtrip`
        -- proofs derived via the universal roundtrip.  Reachable from
        -- Main.agda via `Properties.Preamble`; the explicit walk root
        -- guards the Format module itself against bit-rot.
        agdaWithRTS "Aletheia/DBC/TextParser/Format/Preamble.agda"
        -- B.3.d Layer 4c: TopStmt-level aggregator dispatcher tree
        -- (parseDBC universal roundtrip).  After 4c task E shipped, the
        -- universal `parseText-on-formatText` lives in
        -- `Substrate/Unsafe.agda` (the SOLE non-`--safe` module in the
        -- project, by deliberate policy: the String-level wrap is the
        -- ONLY consumer of `toList∘fromList`, so co-locating it with
        -- the axiom keeps the trusted-surface count at one).  This walk
        -- root transitively covers the entire Aggregator subtree:
        --   * `Substrate/Unsafe` → `Aggregator/Universal` (`--safe`,
        --     full `parseTextChars-on-formatChars` proof).
        --   * `Universal` → `Dispatcher` / `ManyTopStmts` / `Partition`
        --     / `Refine` / `BodyBridge` / `Foundations`.
        --   * `Dispatcher` → `Dispatcher/Simple` (5 simple dispatchers)
        --     + `Dispatcher/Attribute/TopStmt` (3-way TAT façade) +
        --     `Dispatcher/Attribute/PrefixHead` (β prefix witness).
        -- One walk root therefore covers what previously took 3.
        -- Walk-root rationale per
        -- `feedback_check_properties_aggregator_walks.md`.
        agdaWithRTS "Aletheia/DBC/TextParser/Properties/Substrate/Unsafe.agda"
        -- LTL
        agdaWithRTS "Aletheia/LTL/JSON/Properties.agda"
        agdaWithRTS "Aletheia/LTL/Adequacy.agda"
        agdaWithRTS "Aletheia/LTL/Adequacy/Pipeline.agda"
        agdaWithRTS "Aletheia/LTL/Coalgebra/Properties.agda"
        agdaWithRTS "Aletheia/LTL/Semantics/MTL.agda"
        agdaWithRTS "Aletheia/LTL/Semantics/Duality.agda"
        agdaWithRTS "Aletheia/LTL/TruthVal/Properties.agda"
        agdaWithRTS "Aletheia/LTL/SignalPredicate/Cache/Properties.agda"
        agdaWithRTS "Aletheia/LTL/SignalPredicate/Evaluation/Properties.agda"
        putInfo "All proof modules type-checked successfully!"

    phony "check-invariants" $ do
        -- Enforce "postulates and Unsafe modules are limited to the
        -- allowlisted B.3.d substrate" project-wide.
        --
        -- Allowlist policy: exactly one Unsafe module is permitted —
        -- `Aletheia/DBC/TextParser/Properties/Substrate/Unsafe.agda`,
        -- which carries the two `String ↔ List Char` bridging axioms
        -- (`toList∘fromList`, `fromList∘toList`) needed to compose the
        -- B.3.d universal roundtrip theorem.  These mirror stdlib's
        -- `Data.String.Unsafe` (proven by `trustMe` under `--with-K`),
        -- which is structurally unprovable in `--safe --without-K`.
        -- Any other `Unsafe`-named module OR any other `^postulate`
        -- line is rejected — adding one requires a paired Shakefile
        -- update and explicit user approval (see
        -- `feedback_no_suppression_without_approval.md`).
        --
        -- The grep below uses -l (filenames only) so we can compare
        -- paths against the allowlist; -r recurses; --include limits
        -- to .agda; -E enables the regex.  grep exits 1 when there
        -- are no matches, so we take Exit + Stdout explicitly and
        -- ignore the exit code.
        let allowedUnsafe =
                ["Aletheia/DBC/TextParser/Properties/Substrate/Unsafe.agda"]
        (Exit _, Stdout postulateOut) <-
            cmd "grep" "-rln" "--include=*.agda" "-E" "^postulate" "src/"
        let postulateFiles = lines (postulateOut :: String)
            stripSrc f = case stripPrefix "src/" f of
                           Just rest -> rest
                           Nothing   -> f
            unauthorisedPostulate =
                filter (\f -> stripSrc f `notElem` allowedUnsafe) postulateFiles
        unless (null unauthorisedPostulate) $ do
            putError $ "^postulate found in non-allowlisted Agda source:\n"
                    ++ unlines unauthorisedPostulate
            error "check-invariants failed"
        -- Two glob forms: "//*.Unsafe.agda" matches dotted suffixes
        -- (e.g. `Foo.Unsafe.agda`); "//Unsafe.agda" matches leaf
        -- `Unsafe.agda` files (the stdlib-style layout used by the
        -- substrate module).  Union of matches is the candidate set.
        unsafeMatches <-
            getDirectoryFiles "src" ["//*.Unsafe.agda", "//Unsafe.agda"]
        let unauthorisedUnsafe =
                filter (`notElem` allowedUnsafe) unsafeMatches
        unless (null unauthorisedUnsafe) $ do
            putError $ "Unauthorised Unsafe-named module(s) found: "
                    ++ show unauthorisedUnsafe
            error "check-invariants failed"
        putInfo $ "Invariants OK: postulates and Unsafe modules limited "
               ++ "to the allowlisted B.3.d substrate."

    phony "check-no-properties-in-runtime" $ do
        -- Runtime modules must not import Properties modules; a Properties
        -- import would transitively pull every lemma into MAlonzo output.
        let runtime = [ "src/Aletheia/Main.agda"
                      , "src/Aletheia/Main/JSON.agda"
                      , "src/Aletheia/Main/Binary.agda"
                      , "src/Aletheia/Protocol/Handlers.agda"
                      ]
        -- Wrap the regex in a singleton list so Shake's `cmd` does not split
        -- it on whitespace (the pattern contains a space between "open" and
        -- "import" and would otherwise become multiple argv entries).
        let pat = ["^open import .*\\.Properties\\b|^import .*\\.Properties\\b"]
        (Exit _, Stdout violations) <-
            cmd "grep" ["-nE"] pat runtime
        unless (null (violations :: String)) $ do
            putError $ "Runtime module imports a Properties module:\n" ++ violations
            error "check-no-properties-in-runtime failed"
        putInfo "No Properties imports in runtime modules."

    phony "count-modules" $ do
        agdaFiles <- getDirectoryFiles "src" ["//*.agda"]
        let n = length agdaFiles
        putInfo $ "Agda modules under src/: " ++ show n

    phony "check-fidelity" $ do
        -- MAlonzo constructor-drift smoke test.
        -- The cabal test-suite constructor-fidelity exercises the binary FFI
        -- path end-to-end with hand-rolled constructor calls; if a MAlonzo
        -- mangled name or constructor arity drifts relative to the shim, the
        -- test fails to compile OR segfaults on first frame.
        need ["build/libaletheia-ffi.so"]
        putInfo "Running MAlonzo constructor-fidelity test..."
        cmd_ (Cwd "haskell-shim") "cabal" "test" "constructor-fidelity"
             "--test-show-details=direct"

    phony "check-erasure" $ do
        -- Guard the FFI marshaling assumptions about MAlonzo output shape.
        -- After R18 cluster 17 (AGDA-B-22.1), CANId proof fields are
        -- `.(…)`-irrelevant — MAlonzo erases the cell entirely, so the
        -- constructors compile to single-Integer shape (no `AgdaAny`
        -- proof slot). Marshal.hs `mkAgdaCanId` constructs without the
        -- second arg. Timestamp comparisons rely on the newtype
        -- compilation to avoid a hot-path allocation.
        -- If either assumption regresses we want a clear early failure
        -- before ConstructorTest runs.
        need ["build/libaletheia-ffi.so"]
        frame <- liftIO $ readFile "build/MAlonzo/Code/Aletheia/CAN/Frame.hs"
        time  <- liftIO $ readFile "build/MAlonzo/Code/Aletheia/Trace/Time.hs"
        -- Single-Integer ctor shape post-R18 cluster 17 — irrelevant proof
        -- erased; reject any reintroduction of an `AgdaAny` proof slot.
        -- Match by absence of the AgdaAny-shaped form rather than positive
        -- presence: MAlonzo formats the data declaration on one line
        -- (`data T_CANId_8 = C_Standard_12 Integer | C_Extended_16 Integer`),
        -- so a positive-presence check would race the formatter.
        let canIdErasure =
              "C_Standard_12 Integer" `isInfixOf` frame &&
              "C_Extended_16 Integer" `isInfixOf` frame &&
              not ("C_Standard_12 Integer AgdaAny" `isInfixOf` frame) &&
              not ("C_Extended_16 Integer AgdaAny" `isInfixOf` frame)
        unless canIdErasure $
          error $ "check-erasure failed: CAN ID constructor shape drifted "
               ++ "from the post-R18-cluster-17 single-Integer form. "
               ++ "Either MAlonzo regressed and re-emits the proof slot, or "
               ++ "the AGDA-B-22.1 `.(…)` irrelevance was reverted. "
               ++ "Marshal.hs mkAgdaCanId assumes single-arg constructors; "
               ++ "fix the source of drift before this regresses end-to-end."
        let tsNewtype = "newtype T_Timestamp_18" `isInfixOf` time
        unless tsNewtype $
          error $ "check-erasure failed: Timestamp is no longer compiled as "
               ++ "a newtype. Trace/Time.agda uses `record ... no-eta-equality` "
               ++ "intentionally so MAlonzo compiles Timestamp comparisons "
               ++ "without a wrapper allocation on the hot path."
        -- Stdlib constructor names used by BinaryOutput.hs.
        -- These are mangled from stdlib's Vec/Sum modules; a stdlib version
        -- bump can silently rename them, breaking pattern matches at runtime.
        vecBase <- liftIO $ readFile "build/MAlonzo/Code/Data/Vec/Base.hs"
        sumBase <- liftIO $ readFile "build/MAlonzo/Code/Data/Sum/Base.hs"
        let vecCtors =
              "C_'91''93'_32"   `isInfixOf` vecBase &&
              "C__'8759'__38"   `isInfixOf` vecBase
        unless vecCtors $
          error $ "check-erasure failed: Vec stdlib constructor names changed. "
               ++ "BinaryOutput.hs pattern-matches on C_'91''93'_32 (nil) and "
               ++ "C__'8759'__38 (cons) — update to match current MAlonzo output."
        let sumCtors =
              "C_inj'8321'_38"  `isInfixOf` sumBase &&
              "C_inj'8322'_42"  `isInfixOf` sumBase
        unless sumCtors $
          error $ "check-erasure failed: Sum stdlib constructor names changed. "
               ++ "BinaryOutput.hs pattern-matches on C_inj'8321'_38 (inj₁) and "
               ++ "C_inj'8322'_42 (inj₂) — update to match current MAlonzo output."
        -- Maybe / Sigma builtin constructor names used by Marshal.hs +
        -- BinaryOutput.hs.  R19 cluster 13 — AGDA-D-30.1 / AGDA-D-GA23.2:
        -- the FFI shim's `unsafeCoerce` sites assume specific MAlonzo
        -- constructor shapes for Agda.Builtin.Maybe and Agda.Builtin.Sigma;
        -- a stdlib bump or builtin-module rename can drift them silently.
        maybeBase <- liftIO $ readFile "build/MAlonzo/Code/Agda/Builtin/Maybe.hs"
        sigmaBase <- liftIO $ readFile "build/MAlonzo/Code/Agda/Builtin/Sigma.hs"
        let maybeCtors =
              "C_nothing_18" `isInfixOf` maybeBase &&
              "C_just_16"    `isInfixOf` maybeBase
        unless maybeCtors $
          error $ "check-erasure failed: Maybe builtin constructor names "
               ++ "changed. Marshal.hs / BinaryOutput.hs pattern-match on "
               ++ "C_nothing_18 / C_just_16 — update to match current "
               ++ "MAlonzo output."
        let sigmaCtors =
              "T_Σ_14"        `isInfixOf` sigmaBase &&
              "C__'44'__32"   `isInfixOf` sigmaBase &&
              "d_fst_28"      `isInfixOf` sigmaBase &&
              "d_snd_30"      `isInfixOf` sigmaBase
        unless sigmaCtors $
          error $ "check-erasure failed: Sigma builtin constructor / "
               ++ "accessor names changed. Marshal.hs / BinaryOutput.hs "
               ++ "rely on T_Σ_14 / C__'44'__32 / d_fst_28 / d_snd_30 — "
               ++ "update to match current MAlonzo output."
        putInfo "Erasure guards OK: CANId single-Integer ctor + Timestamp newtype + stdlib constructors + Maybe/Sigma builtins."

    phony "check-ffi-exports" $ do
        -- Diff MAlonzo-mangled FFI export names against the checked-in
        -- `haskell-shim/ffi-exports.snapshot`. Guards against silent drift
        -- when Agda definitions are reordered or new definitions are added
        -- above existing exports. Complements `checkFFINames` (run inline
        -- during the Main.hs build rule), which keeps AletheiaFFI.hs in
        -- sync with the mangled names.
        --
        -- R20 cluster I — AGDA-D-30.1.  Each non-blank, non-`#` snapshot
        -- line carries one of three kind prefixes:
        --   * `F: <module>:<name>` — function export (`d_*`).  Validated
        --     by `(name ++ " ::") isInfixOf module-source`.
        --   * `C: <module>:<name>` — data constructor tag (`C_*`).
        --     Validated against the data declaration's alternatives.
        --   * `T: <module>:<name>` — type tag (`T_*`).  Validated against
        --     the `data` / `newtype` declaration header.
        -- Lines with no prefix are treated as `F:` for back-compat with
        -- the pre-R20 snapshot format.
        need ["build/MAlonzo/Code/Aletheia/Main.hs"]
        let snapshotFile = "haskell-shim/ffi-exports.snapshot"
        snapshotContent <- liftIO $ readFile snapshotFile
        let parseSnapshotLine l =
                let s = strip l
                in if null s || "#" `isPrefixOf` s
                   then Nothing
                   else
                     let (kind, body) = case stripPrefix "F: " s of
                                          Just rest -> ("F", rest)
                                          Nothing -> case stripPrefix "C: " s of
                                            Just rest -> ("C", rest)
                                            Nothing -> case stripPrefix "T: " s of
                                              Just rest -> ("T", rest)
                                              Nothing -> ("F", s)  -- back-compat
                     in case break (== ':') body of
                          (m, ':':n) -> Just (kind, m, n)
                          _          -> Nothing
        let expected =
                [ p
                | Just p <- map parseSnapshotLine (lines snapshotContent)
                ]
        -- Load every module mentioned in the snapshot, not just those in
        -- `ffiExports`.  R19 cluster 13 — AGDA-D-30.2 extended the snapshot
        -- to cover indirect helper accessors (Sigma fst/snd, DLC, Rational
        -- numerator/denominator, BatchExtraction values/errors/absent);
        -- R20 cluster I — AGDA-D-30.1 added constructor / type tags for
        -- the load-bearing MAlonzo types that AletheiaFFI.hs constructs
        -- or unsafe-coerces through (StreamState, CANId, DLC, Sum, etc.)
        -- — these are NOT in `ffiExports` because they are not `foreign
        -- export` targets, only their constructor numbering is.
        let snapshotModules = nub [m | (_, m, _) <- expected]
        moduleContents <- liftIO $ forM snapshotModules $ \m -> do
            let path = "build/MAlonzo/Code" </> m <.> "hs"
            existsHere <- SysDir.doesFileExist path
            if existsHere
              then do c <- readFile path; return (m, Just c)
              else return (m, Nothing)
        -- A constructor / type tag is "present" if the mangled name
        -- appears in the expected position in the MAlonzo output.  We
        -- check a small family of contexts to tolerate MAlonzo's
        -- per-version formatting variation.
        let funcPresent name c = (name ++ " ::") `isInfixOf` c
            ctorPresent name c =
                (" " ++ name ++ " ")  `isInfixOf` c
             || (" " ++ name ++ "\n") `isInfixOf` c
             || ("\n" ++ name ++ " ") `isInfixOf` c  -- continuation after `|\n   `
             || ("(" ++ name ++ " ") `isInfixOf` c
             || ("(" ++ name ++ ")") `isInfixOf` c
            typePresent name c =
                ("data "    ++ name ++ " ")  `isInfixOf` c
             || ("data "    ++ name ++ "\n") `isInfixOf` c
             || ("newtype " ++ name ++ " ")  `isInfixOf` c
             || ("newtype " ++ name ++ "\n") `isInfixOf` c
            entryPresent kind name c = case kind of
                "F" -> funcPresent name c
                "C" -> ctorPresent name c
                "T" -> typePresent name c
                _   -> False
        let failures =
              [ (kind, modName, mangled)
              | (kind, modName, mangled) <- expected
              , Just mc <- [lookup modName moduleContents]
              , case mc of
                  Just c  -> not (entryPresent kind mangled c)
                  Nothing -> True
              ]
        unless (null failures) $ do
            forM_ failures $ \(kind, m, expected') ->
                putError $ unlines
                    [ ""
                    , "════════════════════════════════════════════════════════════════"
                    , "ERROR: FFI " ++ kindLabel kind ++ " snapshot drift in " ++ m
                    , "════════════════════════════════════════════════════════════════"
                    , ""
                    , "  Expected (snapshot): " ++ kind ++ ": " ++ m ++ ":" ++ expected'
                    , ""
                    , "  Snapshot file: " ++ snapshotFile
                    , ""
                    , "  If the drift is intentional, regenerate:"
                    , "    cabal run shake -- regen-ffi-exports"
                    , ""
                    , "════════════════════════════════════════════════════════════════"
                    , ""
                    ]
            error "check-ffi-exports failed: snapshot mismatch"
        putInfo $ "FFI exports match snapshot: "
               ++ show (length expected) ++ " entries ("
               ++ show (length [() | ("F", _, _) <- expected]) ++ " functions, "
               ++ show (length [() | ("C", _, _) <- expected]) ++ " constructors, "
               ++ show (length [() | ("T", _, _) <- expected]) ++ " types)."

    phony "regen-ffi-exports" $ do
        -- Rewrite the F: function entries in `haskell-shim/ffi-exports.snapshot`
        -- in-place from the current MAlonzo output.  Run after an intentional
        -- Agda refactor that changes the mangled numbers.
        --
        -- Preservation contract (R20 cluster I follow-up — the original regen
        -- iterated only `ffiExports` and overwrote the whole file, which would
        -- have silently dropped every C: constructor / T: type / indirect F:
        -- helper line on first re-run):
        --
        --   * Lines without an `F: ` prefix (header comments, blanks, section
        --     dividers, `C: …`, `T: …`) are copied through verbatim.
        --   * `F: <module>:d_<funcName>_NN` lines whose `<module>` and
        --     `<funcName>` match an entry in `ffiExports` get their NN
        --     refreshed from MAlonzo.
        --   * `F: …` lines that do NOT match any `ffiExports` entry (the
        --     R19 cluster 13 indirect-helper block) are preserved verbatim.
        --   * If an `ffiExports` entry has no matching `F:` line in the
        --     snapshot (newly added export), we error out with a placeholder
        --     suggestion rather than silently dropping it.
        need ["build/MAlonzo/Code/Aletheia/Main.hs"]
        moduleContents <- loadFFIModuleContents
        let freshFor e = do
                c <- lookup (ffiModule e) moduleContents
                extractMangledName (ffiFuncName e) c
            missingMangle =
                [ ffiFuncName e ++ " (" ++ ffiModule e ++ ")"
                | e <- ffiExports
                , case freshFor e of { Just _ -> False; Nothing -> True }
                ]
        unless (null missingMangle) $
            error $ "regen-ffi-exports: could not extract mangled name for: "
                 ++ unwords missingMangle
        let freshEntries :: [(FFIExport, String)]
            freshEntries =
                [ (e, n) | e <- ffiExports, Just n <- [freshFor e] ]
            rewriteLine line =
                case stripPrefix "F: " line of
                    Nothing   -> (line, Nothing)
                    Just body ->
                        case [ (i, e, n)
                             | (i, (e, n)) <- zip [0 :: Int ..] freshEntries
                             , (ffiModule e ++ ":d_" ++ ffiFuncName e ++ "_")
                                 `isPrefixOf` body
                             ] of
                            ((i, e, n):_) ->
                                ( "F: " ++ ffiModule e ++ ":" ++ n
                                , Just i
                                )
                            [] -> (line, Nothing)  -- indirect helper; preserve
        existing <- liftIO $ do
            c <- readFile "haskell-shim/ffi-exports.snapshot"
            length c `seq` return c  -- force read; we writeFile to same path below
        let (rewrittenLines, hits) =
                unzip (map rewriteLine (lines existing))
            matched = nub [i | Just i <- hits]
            unmatched =
                [ e | (i, (e, _)) <- zip [0 :: Int ..] freshEntries
                    , i `notElem` matched
                ]
        unless (null unmatched) $
            error $ unlines $
                [ "regen-ffi-exports: these ffiExports entries have no F: line"
                , "in the snapshot.  Add a placeholder before re-running:"
                , ""
                ] ++
                [ "    F: " ++ ffiModule e ++ ":d_" ++ ffiFuncName e ++ "_0"
                | e <- unmatched
                ]
        liftIO $ writeFile "haskell-shim/ffi-exports.snapshot"
                           (unlines rewrittenLines)
        putInfo $ "Regenerated snapshot: refreshed "
               ++ show (length matched) ++ " F: function entries; "
               ++ "preserved "
               ++ show (length (lines existing) - length matched)
               ++ " non-function lines (C: / T: / indirect F: helpers / comments)."

    phony "check-stdlib-version" $ do
        -- Verify that the globally installed agda-stdlib matches the
        -- version pinned in `aletheia.agda-lib`. Parses `depend:` from
        -- aletheia.agda-lib, then scans libraries listed in
        -- `$HOME/.agda/libraries` and reads each referenced `.agda-lib`
        -- for its `name:` field. Succeeds iff every required dep matches
        -- at least one installed library. Multi-line `depend:` blocks
        -- (indented continuation lines) are not supported — Aletheia
        -- currently depends only on standard-library on a single line.
        aletheiaLib <- liftIO $ readFile "aletheia.agda-lib"
        let requiredDeps =
              concat [ words rest
                     | l <- lines aletheiaLib
                     , Just rest <- [stripPrefix "depend:" l]
                     ]
        when (null requiredDeps) $
            error "aletheia.agda-lib: no `depend:` line or empty value"
        home <- liftIO getHomeDirectory
        let librariesFile = home </> ".agda" </> "libraries"
        libExists <- doesFileExist librariesFile
        unless libExists $
            error $ "check-stdlib-version failed: "
                 ++ librariesFile ++ " not found. "
                 ++ "Set up Agda libraries config "
                 ++ "(see docs/development/BUILDING.md)"
        libContent <- liftIO $ readFile librariesFile
        let expandHome p = case stripPrefix "~/" p of
                               Just rest -> home </> rest
                               Nothing   -> p
        let paths = [ expandHome s
                    | l <- lines libContent
                    , let s = strip l
                    , not (null s)
                    ]
        names <- forM paths $ \p -> do
            ex <- doesFileExist p
            if ex then do
                c <- liftIO $ readFile p
                let nm = case [ strip w
                              | l <- lines c
                              , Just rest <- [stripPrefix "name:" l]
                              , w <- take 1 (words rest)
                              ] of
                           (n:_) -> n
                           []    -> ""
                return (p, nm)
            else return (p, "")
        let missing =
              [ required
              | required <- requiredDeps
              , null [p | (p, nm) <- names, nm == required]
              ]
        unless (null missing) $ do
            let detail = unlines
                    [ "  " ++ p ++ ": "
                       ++ (if null nm then "<missing or unreadable>" else nm)
                    | (p, nm) <- names
                    ]
            error $ unlines
                [ ""
                , "════════════════════════════════════════════════════════════════"
                , "ERROR: stdlib version mismatch"
                , "════════════════════════════════════════════════════════════════"
                , ""
                , "  aletheia.agda-lib requires: " ++ unwords requiredDeps
                , "  Missing: " ++ unwords missing
                , "  Installed libraries from " ++ librariesFile ++ ":"
                , detail
                , "  Fix: install the missing dependency and register it in "
                , "  " ++ librariesFile
                , ""
                , "════════════════════════════════════════════════════════════════"
                , ""
                ]
        putInfo $ "Stdlib version OK: " ++ unwords requiredDeps

    phony "check-changelog" $ do
        -- R18 Universal Rule UR-1 enforcement (Public API stability and
        -- CHANGELOG discipline).  Detects public-API drift since merge-base
        -- with `main` and fails if CHANGELOG.md was not also modified.
        --
        -- Implementation lives in tools/check_changelog.py so the same
        -- gate can be invoked from the pre-push hook and from local CI
        -- without rebuilding the Shake binary.  Branch-level granularity
        -- (one CHANGELOG commit covers any number of public-API commits
        -- on the same branch).
        cmd_ "python3" "tools/check_changelog.py"

    phony "check-gate-claim" $ do
        -- Gate-claim integrity enforcer (R18 cluster 1 phase 2).
        -- Mechanical enforcer for `memory/feedback_gate_claim_integrity.md`.
        -- When a commit message contains a gate-clean assertion ("all gates
        -- clean", "gates green", etc.), verify that build/libaletheia-ffi.so
        -- mtime postdates every build-relevant staged source file's mtime.
        --
        -- Defaults to HEAD-mode when invoked via Shake (pre-commit mode is
        -- only meaningful inside the actual pre-commit hook context).
        cmd_ "python3" "tools/check_gate_claim.py" "HEAD"

    phony "check-runbook" $ do
        -- Runbook coverage gate (R18 cluster 4).  AGENTS.md cat 22 mandates
        -- that every structured log event the bindings emit has a matching
        -- entry in docs/operations/RUNBOOK.md.  This script parses
        -- docs/LOG_EVENTS.yaml and verifies every event name appears as a
        -- `#### `<name>`` heading in the runbook.  Missing entries fail the
        -- gate — operators must not be left blind on an event the code emits.
        cmd_ "python3" "tools/check_runbook_coverage.py"

    phony "check-limits-parity" $ do
        -- Limits SSOT parity gate (post-R20 DEFERRALS sweep).  The Agda
        -- `Aletheia.Limits` module is the single source of truth for every
        -- adversarial-input bound (AGENTS.md universal rule).  The Go
        -- binding mirrors a subset at `go/aletheia/limits.go` for
        -- cgo-boundary pre-rejection — its header claims "mirrored here
        -- verbatim", and this script enforces that promise.  Python and
        -- C++ bindings consume bounds via the typed `InputBoundExceeded`
        -- error returned from the kernel; they have no local mirror and
        -- are out of scope for this gate.  Failing on: missing required
        -- mirror, numeric value mismatch, BoundKind wire-string mismatch,
        -- or any side having an entry the other side lacks (with explicit
        -- categorisation in NAME_MAPPING).
        cmd_ "python3" "tools/check_limits_parity.py"

    phony "check-stability-bench" $ do
        -- Stability-bench coverage gate (R18 cluster 6).  AGENTS.md cat 16 /
        -- 25 / 26 / 27 mandate per-binding long-run leak detection harnesses
        -- (RSS, FD, threads/goroutines, malloc_info, StablePtr / ctypes /
        -- logger handlers).  This script parses docs/STABILITY_BENCH.yaml
        -- and verifies every (binding, sub_check) pair's source_marker is
        -- present in the named harness file — catches silent removal
        -- without running the harnesses.  The dynamic counterpart that
        -- actually runs the bench is `tools/stability_run.py`, gated
        -- behind ALETHEIA_STABILITY_CHECK=1 in `tools/run_ci.py`.
        cmd_ "python3" "tools/check_stability_bench.py"

    phony "check-mutation-setup" $ do
        -- Mutation-setup coverage gate (R18 cluster 7).  AGENTS.md cat 14(g)
        -- mandates per-binding mutation testing on hot-path modules.  This
        -- script parses docs/MUTATION_BENCH.yaml and verifies every declared
        -- hot-path source file exists on disk — catches silent removal /
        -- rename of a hot-path file (e.g. a future protocols-split move that
        -- relocates `aletheia/client/_client.py`) without running the
        -- mutation tools (each binding's tool takes 30 min - 2 hours).
        -- Dynamic counterpart that actually runs mutmut / go-mutesting /
        -- Mull is `tools/mutation_run.py`, gated behind
        -- ALETHEIA_MUTATION_CHECK=1 (or `--mutation`) in `tools/run_ci.py`.
        cmd_ "python3" "tools/check_mutation_setup.py"

    phony "check-bound-enforcement" $ do
        -- Adversarial-input bound enforcement gate (R20 cluster I /
        -- AGDA-D-32.5).  AGENTS.md universal rule "Adversarial-input bounds
        -- at parser surfaces" requires every `BoundKind` ctor in
        -- `Aletheia.Limits` to surface as a typed
        -- `Error.InputBoundExceeded <Ctor> observed limit` at some parser
        -- or handler boundary.  This script parses the `data BoundKind`
        -- ADT and greps for `InputBoundExceeded <Ctor>` emit sites under
        -- `src/`; a ctor with zero sites is dead metadata (the wire code
        -- is unreachable) and fails the gate.
        cmd_ "python3" "tools/check_bound_enforcement.py"

    -- The full offline CI sweep is invoked directly via `tools/run_ci.py`,
    -- NOT through a Shake `phony "ci"` target.
    --
    -- Reason: run_ci.py internally calls `cabal run shake -- build`,
    -- `cabal run shake -- check-properties`, etc.  If invoked through
    -- a Shake phony (parent: `cabal run shake -- ci`), the inner
    -- `cabal run` fails immediately because cabal-install's flock on
    -- `dist-newstyle/` is held by the outer process.
    --
    -- Two stable invocation paths:
    --   * Direct:    `tools/run_ci.py`     (pre-push hook, manual runs)
    --   * Per-gate:  `cabal run shake -- check-properties` (etc.)

    phony "dist" $ do
        -- CICD-5.2 (R23): dist must NOT ship a tarball that skipped the proof
        -- tree.  Pre-push hook is the canonical defense; bind the proof gates
        -- here too as defense-in-depth so direct `cabal run shake -- dist`
        -- invocations cannot side-step them.  Adds ~10 min to a release cut.
        need ["check-properties",
              "check-invariants",
              "check-no-properties-in-runtime",
              "check-erasure",
              "check-fidelity",
              "check-ffi-exports",
              "build/libaletheia-ffi.so"]

        let distDir = "dist/aletheia"
        let distLib = distDir </> "lib"
        let distInclude = distDir </> "include"
        let tarball = "dist/aletheia.tar.gz"
        let manifestFile = distDir </> "MANIFEST.txt"
        let sbomFile = distDir </> "aletheia-sbom.cdx.json"
        let tarHashFile = tarball ++ ".sha256"
        let tarSigFile = tarball ++ ".sig"

        -- Clean previous dist
        liftIO $ removePathForcibly distDir
        liftIO $ removePathForcibly tarball
        liftIO $ removePathForcibly tarHashFile
        liftIO $ removePathForcibly tarSigFile
        liftIO $ createDirectoryIfMissing True distLib
        liftIO $ createDirectoryIfMissing True distInclude

        -- UR-3.2: record source-side hash (pre-strip, pre-patchelf) — anchors
        -- the chain-of-custody from build/libaletheia-ffi.so to dist tarball.
        sourceHash <- sha256file "build/libaletheia-ffi.so"

        -- Copy main .so and GHC runtime dependencies
        putInfo "Packaging distribution..."
        cmd_ "cp" "build/libaletheia-ffi.so" distLib
        ghcDeps <- getGhcDeps "build/libaletheia-ffi.so"
        forM_ ghcDeps $ \dep ->
            cmd_ "cp" "-L" dep distLib

        let mainSoDist = distLib </> "libaletheia-ffi.so"

        -- CICD-4.1: hash-verify post-copy matches source (catches a transient
        -- copy corruption between unpackaged .so and packaged dist).
        copyHash <- sha256file mainSoDist
        when (copyHash /= sourceHash) $
            error $ "dist: post-copy hash drift (source " ++ sourceHash ++
                    " vs copy " ++ copyHash ++ ")"

        -- CICD-2.1: cache .so file list once instead of two find invocations.
        Stdout rawSoFiles <- cmd Shell ("find " ++ distLib ++ " -name '*.so*' -type f")
        let soFiles = filter (not . null) (lines rawSoFiles)

        -- Patch RUNPATH so all .so files find each other via $ORIGIN
        Exit patchelfCode <- cmd Shell "command -v patchelf >/dev/null 2>&1"
        case patchelfCode of
            ExitSuccess ->
                forM_ soFiles $ \f ->
                    cmd_ "patchelf" "--set-rpath" "$ORIGIN" f
            ExitFailure _ ->
                putWarn "patchelf not found — skipping RPATH patching. Set LD_LIBRARY_PATH at runtime."

        -- Strip debug symbols to reduce size (--strip-unneeded, NOT --strip-all:
        -- --strip-all would remove the C export symbols needed by dlsym)
        Exit stripCode <- cmd Shell "command -v strip >/dev/null 2>&1"
        case stripCode of
            ExitSuccess -> do
                putInfo "Stripping debug symbols..."
                forM_ soFiles $ \f ->
                    cmd_ "strip" "--strip-unneeded" f
            ExitFailure _ ->
                putWarn "strip not found — keeping debug symbols."

        -- Copy C header
        cmd_ "cp" "include/aletheia.h" distInclude

        -- UR-3.2: post-strip / post-patchelf hashes — bytes that ship in the
        -- tarball.  `finalHash` is the load-bearing artifact identity.
        finalHash <- sha256file mainSoDist
        depHashes <- forM soFiles $ \f -> do
            h <- sha256file f
            return (takeFileName f, h)

        -- Toolchain pin metadata.  Build-date is the commit time, NOT the
        -- wall-clock at dist invocation — wall-clock would defeat artifact-
        -- level reproducibility (two dist runs of the same commit would yield
        -- different MANIFEST.txt content → different tarball hash).
        Stdout gitCommit  <- cmd Shell "git rev-parse HEAD"
        Stdout gitDirty   <- cmd Shell "git status --porcelain"
        Stdout commitTime <- cmd Shell "git log -1 --format=%ct HEAD"
        let commitEpoch = strip commitTime
        Stdout buildDate  <- cmd Shell ("date -u -Iseconds -d @" ++ commitEpoch)
        Stdout ghcVer    <- cmd Shell "ghc --numeric-version"
        Stdout cabalVer  <- cmd Shell "cabal --numeric-version"
        -- agda --version emits multi-line output (version + cabal flag list);
        -- take only the first line.
        Stdout agdaVer   <- cmd Shell "agda --version | head -n1"
        Stdout agdaLib   <- cmd Shell "grep '^depend:' aletheia.agda-lib | sed 's/depend://'"
        let gitTreeStatus = if null (strip gitDirty) then "clean" else "dirty"
        let pad n s = s ++ replicate (max 0 (n - length s)) ' '
        let readmeFile = distDir </> "README.txt"
        let readmeText = unlines
                [ "Aletheia"
                , "========"
                , ""
                , "This tarball ships a pre-built Aletheia release artifact."
                , ""
                , "Contents:"
                , "  lib/libaletheia-ffi.so     Verified Agda kernel + GHC runtime"
                , "  lib/libHS*.so              GHC runtime dependencies (RPATH=$ORIGIN)"
                , "  include/aletheia.h         C header (consumed by Python/C++/Go bindings)"
                , "  MANIFEST.txt               Toolchain pin + per-artifact SHA-256 hashes"
                , "  aletheia-sbom.cdx.json     CycloneDX 1.5 software bill of materials"
                , ""
                , "Quick start (from the unpacked tarball):"
                , "  gcc -Iinclude -Llib -Wl,-rpath,'$ORIGIN/../lib' -laletheia-ffi app.c"
                , ""
                , "Verification (verify-then-trust order):"
                , "  1. Tarball signature (cosign + keys/cosign.pub from the source tree)"
                , "  2. sha256sum -c aletheia.tar.gz.sha256"
                , "  3. After unpacking: hashes inside MANIFEST.txt vs find lib -name '*.so*'"
                , ""
                , "Full integration guide:"
                , "  docs/development/DISTRIBUTION.md (in the source repo)"
                , ""
                , "Release process and signing key rotation:"
                , "  docs/development/RELEASE.md (in the source repo)"
                , ""
                , "Build provenance (this artifact):"
                , "  Git commit:  " ++ strip gitCommit
                , "  Git tree:    " ++ gitTreeStatus
                , "  Build date:  " ++ strip buildDate ++ "  (commit time, NOT wall-clock)"
                ]
        liftIO $ writeFile readmeFile readmeText

        let manifestText = unlines $
                [ "Aletheia distribution manifest"
                , "=============================="
                , ""
                , "Generated:   " ++ strip buildDate
                , "Git commit:  " ++ strip gitCommit
                , "Git tree:    " ++ gitTreeStatus
                , ""
                , "Toolchain (pinned for reproducible build):"
                , "  GHC:           " ++ strip ghcVer
                , "  cabal-install: " ++ strip cabalVer
                , "  Agda:          " ++ strip agdaVer
                , "  Agda stdlib:   " ++ strip agdaLib
                , ""
                , "Source artifact (pre-strip, pre-patchelf):"
                , "  build/libaletheia-ffi.so          " ++ sourceHash
                , ""
                , "Distribution artifacts (post-strip, post-patchelf):"
                ] ++ map (\(n, h) -> "  " ++ pad 34 n ++ h) depHashes ++
                [ ""
                , "Verification:"
                , "  Distribution integrity (compare against this manifest):"
                , "    find lib/ -name '*.so*' -exec sha256sum {} \\;"
                , "  Tarball signature (local dev, signed without tlog):"
                , "    cosign verify-blob --insecure-ignore-tlog \\"
                , "      --key keys/cosign.pub \\"
                , "      --signature aletheia.tar.gz.sig aletheia.tar.gz"
                , "  Tarball signature (release, signed with ALETHEIA_COSIGN_TLOG=1):"
                , "    cosign verify-blob --key keys/cosign.pub \\"
                , "      --signature aletheia.tar.gz.sig aletheia.tar.gz"
                , ""
                , "Reference:"
                , "  AGENTS.md § Universal Rules → Reproducible build verification"
                , "  docs/development/RELEASE.md § Verifying release artifacts"
                ]
        liftIO $ writeFile manifestFile manifestText

        -- UR-3.2 / CICD-5.3: SBOM (CycloneDX 1.5).  Pass the git commit epoch
        -- as --source-epoch so the SBOM timestamp + UUID5 are derived from
        -- source state, not wall-clock — required for artifact-level repro.
        putInfo "Generating SBOM..."
        let distGhcDeps = map (\dep -> distLib </> takeFileName dep) ghcDeps
        cmd_ "python3" "tools/sbom_generate.py"
            "--repo" "."
            "--main-so" mainSoDist
            "--out" sbomFile
            "--source-epoch" commitEpoch
            distGhcDeps

        -- Reproducible tarball: sort entries + pin mtime to the git commit time
        -- + zero owner/group.  Use `gzip -n` to suppress gzip's per-invocation
        -- timestamp embed (the gzip header MTIME field defaults to current
        -- wall-clock if -n is not set).  Without these flags `tar czf` embeds
        -- wall-clock mtime, the invoking user's uid/gid, and the gzip wall-
        -- clock — three orthogonal sources defeating tarball-level repro.
        let mtime = "@" ++ commitEpoch
        putInfo $ "Creating reproducible tarball (mtime=" ++ mtime ++ ")..."
        cmd_ "tar"
            "--sort=name"
            ("--mtime=" ++ mtime)
            "--owner=0" "--group=0" "--numeric-owner"
            ("--use-compress-program=gzip -n")
            "-cf" tarball
            "-C" "dist" "aletheia/"

        -- CICD-5.2: side-car SHA-256 for the tarball, suitable for sha256sum -c.
        tarballHash <- sha256file tarball
        liftIO $ writeFile tarHashFile (tarballHash ++ "  " ++ takeFileName tarball ++ "\n")

        -- CICD-5.4: sign the tarball if cosign + key are available.  Skip-with-
        -- warning when either is missing — release verification fails closed
        -- on the consumer side via cosign verify-blob, not here.
        cosignKey <- liftIO $ lookupEnv "ALETHEIA_COSIGN_KEY"
        Exit cosignCode <- cmd Shell "command -v cosign >/dev/null 2>&1"
        sigPresent <- case (cosignCode, cosignKey) of
            (ExitSuccess, Just keyPath) -> do
                -- Default --tlog-upload=false: per-dev-run signing should not
                -- push every artifact hash to the public Sigstore Rekor log.
                -- Release signing opts back in via ALETHEIA_COSIGN_TLOG=1.
                tlogEnv <- liftIO $ lookupEnv "ALETHEIA_COSIGN_TLOG"
                let tlogFlag = case tlogEnv of
                        Just "1" -> "--tlog-upload=true"
                        _        -> "--tlog-upload=false"
                putInfo $ "Signing tarball with cosign (" ++ tlogFlag ++ ")..."
                cmd_ Shell $
                    "COSIGN_PASSWORD=\"${COSIGN_PASSWORD:-}\" cosign sign-blob --yes " ++
                    tlogFlag ++
                    " --key '" ++ keyPath ++ "'" ++
                    " --output-signature '" ++ tarSigFile ++ "'" ++
                    " '" ++ tarball ++ "'"
                return True
            (ExitSuccess, Nothing) -> do
                putWarn $ "ALETHEIA_COSIGN_KEY env var not set — skipping artifact signing.\n" ++
                    "  See docs/development/RELEASE.md § Signing for the canonical key path."
                return False
            (ExitFailure _, _) -> do
                putWarn "cosign not found — skipping artifact signing. Install: see docs/development/RELEASE.md."
                return False

        -- Report
        Stdout distSize <- cmd Shell ("du -sh " ++ distDir ++ " | cut -f1")
        Stdout tarSize <- cmd Shell ("du -sh " ++ tarball ++ " | cut -f1")
        let nDeps = length ghcDeps
        putInfo ""
        putInfo "════════════════════════════════════════════════════════════════"
        putInfo "  Distribution packaged"
        putInfo "════════════════════════════════════════════════════════════════"
        putInfo ""
        putInfo $ "  dist/aletheia/           (" ++ strip distSize ++ ")"
        putInfo $ "    lib/libaletheia-ffi.so   (main library, sha256 " ++ take 12 finalHash ++ "...)"
        putInfo $ "    lib/libHS*.so            (" ++ show nDeps ++ " GHC runtime deps, RPATH=$ORIGIN)"
        putInfo $ "    include/aletheia.h       (C header)"
        putInfo $ "    MANIFEST.txt             (UR-3.2 hashes + toolchain pin)"
        putInfo $ "    aletheia-sbom.cdx.json   (CycloneDX 1.5 SBOM)"
        putInfo $ "    README.txt               (consumer entry point — verification + quick start)"
        putInfo $ "  dist/aletheia.tar.gz     (" ++ strip tarSize ++ ", sha256 " ++ take 12 tarballHash ++ "...)"
        putInfo $ "  dist/aletheia.tar.gz.sha256"
        when sigPresent $
            putInfo $ "  dist/aletheia.tar.gz.sig (cosign signature; verify with keys/cosign.pub)"
        putInfo ""
        putInfo "  Verify:"
        putInfo $ "    sha256sum -c " ++ tarHashFile
        when sigPresent $ do
            putInfo $ "    # Local dev (tlog skipped per --tlog-upload=false at sign time):"
            putInfo $ "    cosign verify-blob --insecure-ignore-tlog --key keys/cosign.pub \\"
            putInfo $ "      --signature " ++ tarSigFile ++ " " ++ tarball
            putInfo $ "    # Release (sign with ALETHEIA_COSIGN_TLOG=1, then verify without --insecure-ignore-tlog)"
        putInfo ""
        putInfo "  Usage (no LD_LIBRARY_PATH needed — RPATH handles resolution):"
        putInfo "    gcc -Idist/aletheia/include -Ldist/aletheia/lib \\"
        putInfo "        -Wl,-rpath,'$ORIGIN/../lib' -laletheia-ffi app.c"
        putInfo ""

    phony "install-python" $ do
        need ["build/libaletheia-ffi.so"]
        -- R19 cluster E2 (CICD-3.1 closure): strip secret env vars
        -- before invoking pip3 so a future CI workflow that wires
        -- this target doesn't leak ambient credentials to the package
        -- index resolver.  Stripped: GitHub Actions auth tokens
        -- (GITHUB_TOKEN / GH_TOKEN / GITHUB_API_URL), Aletheia signing
        -- credentials (ALETHEIA_COSIGN_KEY / ALETHEIA_COSIGN_TLOG),
        -- and the generic CI auth knobs (TWINE_PASSWORD / NPM_TOKEN).
        cmd_ (Cwd "python")
            (RemEnv "GITHUB_TOKEN") (RemEnv "GH_TOKEN")
            (RemEnv "GITHUB_API_URL")
            (RemEnv "ALETHEIA_COSIGN_KEY") (RemEnv "ALETHEIA_COSIGN_TLOG")
            (RemEnv "TWINE_PASSWORD") (RemEnv "NPM_TOKEN")
            "pip3 install -e ."

    phony "docker" $ do
        need ["dist"]
        -- CICD-5.5: tag with both `latest` (moving) AND `<short-sha>` (immutable)
        -- so consumers can pin by commit.  Base image is digest-pinned in
        -- Dockerfile.runtime; the local image tag here is the consumer-facing
        -- handle.
        Stdout shortSha <- cmd Shell "git rev-parse --short HEAD"
        let shaTag = "aletheia:" ++ strip shortSha
        putInfo $ "Building Docker runtime image (tags: aletheia:latest, " ++ shaTag ++ ")..."
        cmd_ "docker" "build"
            "-t" "aletheia:latest"
            "-t" shaTag
            "-f" "Dockerfile.runtime" "."
        Stdout imageSize <- cmd Shell "docker images aletheia:latest --format '{{.Size}}'"

        -- CICD-A-5.4 R23 closure: emit an OCI-image SBOM alongside the
        -- existing dist tarball SBOM.  Three image-layer pins augment the
        -- dist SBOM: the built image's content-addressed SHA-256, the
        -- digest-pinned base image (parsed from `FROM ...@sha256:...`),
        -- and the libgmp10 Debian version (parsed from the `apt-get
        -- install` line).  All three are reproducible-build inputs the
        -- consumer needs to verify image provenance.
        Stdout imageIdRaw <- cmd Shell "docker images aletheia:latest --no-trunc --format '{{.ID}}'"
        Stdout commitTimeRaw <- cmd Shell "git log -1 --pretty=%ct"
        dockerfile <- liftIO $ readFile "Dockerfile.runtime"
        ghcDepsDocker <- getGhcDeps "build/libaletheia-ffi.so"
        let imageId       = strip imageIdRaw
            commitEpochD  = strip commitTimeRaw
            imageBase     = parseFromBase dockerfile
            imageLibgmp   = parseLibgmpVersion dockerfile
            imageSbomFile = "build/docker/aletheia-image-sbom.cdx.json"
            distLibDocker = "dist/aletheia/lib"
            distGhcDepsDocker = map (\dep -> distLibDocker </> takeFileName dep) ghcDepsDocker
        liftIO $ createDirectoryIfMissing True (takeDirectory imageSbomFile)
        putInfo $ "Generating image SBOM (" ++ imageSbomFile ++ ")..."
        cmd_ "python3" "tools/sbom_generate.py"
            "--repo" "."
            "--main-so" (distLibDocker </> "libaletheia-ffi.so")
            "--out" imageSbomFile
            "--source-epoch" commitEpochD
            "--image-id" imageId
            "--image-base" imageBase
            "--image-libgmp" imageLibgmp
            distGhcDepsDocker

        putInfo ""
        putInfo "════════════════════════════════════════════════════════════════"
        putInfo $ "  Docker image: aletheia:latest (" ++ strip imageSize ++ ")"
        putInfo $ "  Pinned tag:   " ++ shaTag
        putInfo $ "  Image ID:     " ++ imageId
        putInfo $ "  Image SBOM:   " ++ imageSbomFile
        putInfo "════════════════════════════════════════════════════════════════"
        putInfo ""
        putInfo "  Run:"
        putInfo "    docker run --rm aletheia:latest python3 -c \\"
        putInfo "      \"from aletheia import AletheiaClient; print('OK')\""
        putInfo $ "  Pin to commit:"
        putInfo $ "    docker run --rm " ++ shaTag ++ " ..."
        putInfo ""

    phony "clean" $ do
        putInfo "Cleaning build artifacts..."
        removeFilesAfter "build" ["//*"]
        removeFilesAfter "src" ["//*.agdai"]
        removeFilesAfter "haskell-shim" ["//MAlonzo"]
        cmd_ (Cwd "haskell-shim") "cabal clean"

    "build/MAlonzo/Code/Aletheia/Main.hs" %> \out -> do
        agdaSources <- getDirectoryFiles "src" ["//*.agda"]
        need (map ("src" </>) agdaSources)

        -- Shake's ChangeModtimeAndDigest tracks file content hashes
        -- When any .agda source changes, Shake detects it and re-runs this rule
        -- Agda will then update .agdai files as needed based on source changes
        putInfo "Compiling Agda to Haskell (this may take a few minutes)..."
        cores <- liftIO getNumProcessors
        cmd_ (Cwd "src")
            "agda"
            "+RTS" ("-N" ++ show cores) "-M16G" "-RTS"
            "--compile"
            "--compile-dir=../build"
            "--ghc-dont-call-ghc"
            "Aletheia/Main.agda"

        exists <- doesFileExist out
        if exists
            then do
                putInfo $ "MAlonzo output generated: " ++ out
                -- Check that FFI wrapper uses correct mangled names
                checkFFINames "haskell-shim/src/AletheiaFFI.hs"
            else error $ "Agda compilation failed: " ++ out ++ " not created"

    phony "create-symlink" $ do
        need ["build/MAlonzo/Code/Aletheia/Main.hs"]

        let symlinkPath = "haskell-shim/MAlonzo"
        let target = "../build/MAlonzo"

        -- Remove existing symlink/directory if present
        liftIO $ removePathForcibly symlinkPath

        putInfo $ "Creating symlink: " ++ symlinkPath ++ " -> " ++ target

        if os == "mingw32"
            then cmd_ "cmd" "/c" "mklink /D" symlinkPath target
            else liftIO $ createDirectoryLink target symlinkPath

    "build/libaletheia-ffi.so" %> \out -> do
        -- Depend on all MAlonzo generated Haskell files
        -- This ensures Shake detects any changes from Agda compilation
        malonzoFiles <- getDirectoryFiles "build" ["MAlonzo//**/*.hs"]
        need (map ("build" </>) malonzoFiles)

        need ["create-symlink"]  -- Depend on phony target, not directory
        need [ "haskell-shim/src/AletheiaFFI.hs"
             , "haskell-shim/src/AletheiaFFI/Marshal.hs"
             , "haskell-shim/src/AletheiaFFI/BinaryOutput.hs"
             , "haskell-shim/test/ConstructorTest.hs"
             , "haskell-shim/aletheia.cabal"
             ]

        -- Force Cabal to rebuild when MAlonzo files change
        -- Touch AletheiaFFI.hs to invalidate Cabal's cache
        putInfo "Invalidating Cabal cache (touch AletheiaFFI.hs)..."
        cmd_ "touch" "haskell-shim/src/AletheiaFFI.hs"

        -- Delete intermediate build artifacts to force relink
        putInfo "Cleaning Cabal build artifacts..."
        Stdout ghcVer <- cmd "ghc" "--numeric-version"
        let ghcTag = "ghc-" ++ strip ghcVer
        cmd_ (Cwd "haskell-shim") Shell $ "rm -rf dist-newstyle/build/*/" ++ ghcTag ++ "/aletheia-*/f/aletheia-ffi"

        putInfo "Building FFI shared library..."
        -- UR-3.3: pass -ffile-prefix-map through to GHC's C compiler so any
        -- C-side debug info / __FILE__ embeddings strip the build-host path.
        -- Cannot use the bare `-fdebug-prefix-map` GHC flag here — that was
        -- only added to GHC in 9.10, and we pin 9.6.7 (see MANIFEST.txt).
        --
        -- Same-host reproducibility was verified empirically WITHOUT this flag
        -- (R18 cluster 3: two clean builds → bit-identical libaletheia-ffi.so),
        -- so the flag is defense-in-depth against future GHC C-side embeds /
        -- enabling debug info on a downstream rebuild.  C++ binding gets the
        -- equivalent flag in cpp/CMakeLists.txt.
        repoRoot <- liftIO getCurrentDirectory
        -- Memory-bound the GHC compilation of MAlonzo .hs files.
        -- `-jN` caps parallelism (each worker = one GHC process); per-worker
        -- `+RTS -M3G -RTS` is the tripwire ceiling — typical MAlonzo modules
        -- compile in 0.3-1 GB, the 3G ceiling fails fast on pathological
        -- growth rather than silently exhausting WSL2's 50%-of-host budget.
        -- Worst-case peak: 16 × 3 GB = 48 GB on a 62 GiB host.  Bump only
        -- if a specific MAlonzo module legitimately needs more (mirror of
        -- the Agda elaborator's -M16G discipline).  -A64M raises GHC's
        -- nursery size from the 4 MB default for slight throughput win.
        -- Wrap in `[String]` so Shake's `cmd_` does NOT whitespace-split
        -- the value (otherwise `+RTS`, `-A64M`, `-M3G`, `-RTS` get sent as
        -- separate argv elements and cabal rejects them as unknown options).
        cmd_ (Cwd "haskell-shim") "cabal" "build" "-j16"
            ("--ghc-options=-optc-ffile-prefix-map=" ++ repoRoot ++ "=.")
            ["--ghc-options=+RTS -A64M -M3G -RTS"]
            "aletheia-ffi"

        -- Find and copy the built .so file
        Stdout soPath <- cmd (Cwd "haskell-shim") Shell
            "find dist-newstyle -name 'libaletheia-ffi.so' -type f | head -1"
        let trimmedPath = strip soPath
        if null trimmedPath
            then error "Could not find libaletheia-ffi.so in dist-newstyle"
            else do
                cmd_ (Cwd "haskell-shim") "cp" trimmedPath ("../" ++ out)
                putInfo $ "Shared library created: " ++ out

    -- =========================================================================
    -- Install / Uninstall targets
    -- =========================================================================

    phony "install" $ do
        need ["build/libaletheia-ffi.so"]

        -- Read PREFIX (default: ~/.local)
        home <- liftIO getHomeDirectory
        prefixEnv <- liftIO $ lookupEnv "PREFIX"
        let prefix = maybe (home </> ".local") id prefixEnv
        configShellEnv <- liftIO $ lookupEnv "CONFIGURE_SHELL"
        let configShell = configShellEnv == Just "1"

        -- Check prerequisites
        checkPrerequisites

        let libDir     = prefix </> "lib" </> "aletheia"
        let docDir     = prefix </> "share" </> "doc" </> "aletheia"
        let exampleDir = prefix </> "share" </> "aletheia" </> "examples"
        let venvDir    = libDir </> "venv"
        let venvPython = venvDir </> "bin" </> "python3"
        let venvPip    = venvDir </> "bin" </> "pip"

        -- Create directory tree
        putInfo $ "Installing to " ++ prefix ++ " ..."
        liftIO $ createDirectoryIfMissing True libDir
        liftIO $ createDirectoryIfMissing True docDir
        liftIO $ createDirectoryIfMissing True exampleDir

        -- Copy main shared library
        putInfo "Copying shared library..."
        cmd_ "cp" "build/libaletheia-ffi.so" libDir

        -- Bundle GHC runtime dependencies (only if not standalone)
        ghcDeps <- getGhcDeps "build/libaletheia-ffi.so"
        if null ghcDeps
            then putInfo "Standalone .so detected — no GHC libraries to bundle."
            else do
                putInfo "Bundling GHC runtime libraries..."
                forM_ ghcDeps $ \dep ->
                    cmd_ "cp" "-L" dep libDir
                -- Patch RUNPATH on all .so files so they find each other via $ORIGIN
                putInfo "Patching RUNPATH on shared libraries..."
                Stdout soFiles <- cmd Shell ("find " ++ libDir ++ " -name '*.so*' -type f")
                forM_ (filter (not . null) (lines soFiles)) $ \f ->
                    cmd_ "patchelf" "--set-rpath" "$ORIGIN" f

        -- Copy C header
        let includeDir = prefix </> "include" </> "aletheia"
        liftIO $ createDirectoryIfMissing True includeDir
        putInfo "Copying C header..."
        cmd_ "cp" "include/aletheia.h" includeDir

        -- Create Python venv
        putInfo "Creating Python virtual environment..."
        cmd_ "python3" "-m" "venv" venvDir
        cmd_ venvPip "install" "--upgrade" "pip" "setuptools" "wheel"

        -- Install aletheia Python package (non-editable)
        putInfo "Installing aletheia Python package..."
        cmd_ venvPip "install" "./python"

        -- Find site-packages and write _install_config.py
        Stdout sitePackages <- cmd venvPython "-c"
            "import site; print(site.getsitepackages()[0])"
        let siteDir = strip sitePackages
        let configFile = siteDir </> "aletheia" </> "_install_config.py"
        let soAbsPath = libDir </> "libaletheia-ffi.so"
        putInfo $ "Writing install config: " ++ configFile
        liftIO $ writeFile configFile $
            "from pathlib import Path\n\nLIBRARY_PATH: Path = Path(" ++ show soAbsPath ++ ")\n"

        -- Copy documentation
        putInfo "Copying documentation..."
        cmd_ Shell ("cp -r docs/* " ++ docDir ++ "/")
        -- Copy root doc files that exist
        forM_ ["README.md", "CONTRIBUTING.md", "LICENSE.md", "LICENSE"] $ \f -> do
            rootDocExists <- doesFileExist f
            when rootDocExists $ cmd_ "cp" f docDir

        -- Copy examples
        putInfo "Copying examples..."
        examplesExist <- doesDirectoryExist "examples"
        when examplesExist $ do
            cmd_ Shell ("cp -r examples/* " ++ exampleDir ++ "/")
            cmd_ Shell ("find " ++ exampleDir ++ " -name '__pycache__' -type d -exec rm -rf {} + 2>/dev/null || true")

        -- Write manifest for uninstall
        let manifestFile = libDir </> "manifest.txt"
        liftIO $ writeFile manifestFile $ unlines
            [ prefix </> "lib" </> "aletheia"
            , prefix </> "share" </> "doc" </> "aletheia"
            , prefix </> "share" </> "aletheia"
            ]

        -- Optionally configure shell aliases
        when configShell $ do
            putInfo "Configuring shell aliases..."
            let venvActivate     = venvDir </> "bin" </> "activate"
            let venvActivateFish = venvDir </> "bin" </> "activate.fish"
            let marker = "# Added by aletheia install"

            -- bash
            let bashrc = home </> ".bashrc"
            bashExists <- doesFileExist bashrc
            when bashExists $ do
                Stdout bashContent <- cmd Shell ("cat " ++ bashrc)
                unless (marker `isInfixOf` bashContent) $ do
                    liftIO $ appendFile bashrc $ unlines
                        [ "", marker
                        , "alias aletheia-env='source " ++ venvActivate ++ "'"
                        ]
                    putInfo $ "  Added alias to " ++ bashrc

            -- zsh
            let zshrc = home </> ".zshrc"
            zshExists <- doesFileExist zshrc
            when zshExists $ do
                Stdout zshContent <- cmd Shell ("cat " ++ zshrc)
                unless (marker `isInfixOf` zshContent) $ do
                    liftIO $ appendFile zshrc $ unlines
                        [ "", marker
                        , "alias aletheia-env='source " ++ venvActivate ++ "'"
                        ]
                    putInfo $ "  Added alias to " ++ zshrc

            -- fish
            let fishConfig = home </> ".config" </> "fish" </> "config.fish"
            fishExists <- doesFileExist fishConfig
            when fishExists $ do
                Stdout fishContent <- cmd Shell ("cat " ++ fishConfig)
                unless (marker `isInfixOf` fishContent) $ do
                    liftIO $ appendFile fishConfig $ unlines
                        [ "", marker
                        , "alias aletheia-env 'source " ++ venvActivateFish ++ "'"
                        ]
                    putInfo $ "  Added alias to " ++ fishConfig

        -- Success banner
        putInfo ""
        putInfo "════════════════════════════════════════════════════════════════"
        putInfo "  Aletheia installed successfully!"
        putInfo "════════════════════════════════════════════════════════════════"
        putInfo ""
        putInfo $ "  Location: " ++ prefix
        putInfo ""
        putInfo "  Activate the environment:"
        putInfo $ "    bash/zsh: source " ++ venvDir </> "bin" </> "activate"
        putInfo $ "    fish:     source " ++ venvDir </> "bin" </> "activate.fish"
        putInfo ""
        putInfo "  Then use:"
        putInfo "    python3 -c \"from aletheia import AletheiaClient; print('OK')\""
        putInfo ""
        putInfo "  Uninstall:"
        putInfo $ "    " ++ (if prefixEnv /= Nothing then "PREFIX=" ++ prefix ++ " " else "")
              ++ "cabal run shake -- uninstall"
        putInfo ""

    phony "uninstall" $ do
        -- Read PREFIX (default: ~/.local)
        home <- liftIO getHomeDirectory
        prefixEnv <- liftIO $ lookupEnv "PREFIX"
        let prefix = maybe (home </> ".local") id prefixEnv
        let manifestFile = prefix </> "lib" </> "aletheia" </> "manifest.txt"

        manifestExists <- doesFileExist manifestFile
        if manifestExists
            then do
                manifestContent <- liftIO $ readFile manifestFile
                let dirs = filter (not . null) (lines manifestContent)
                forM_ dirs $ \dir -> do
                    dirExists <- doesDirectoryExist dir
                    when dirExists $ do
                        putInfo $ "Removing " ++ dir ++ " ..."
                        liftIO $ removeDirectoryRecursive dir
                -- Clean up empty parent dirs
                let shareAletheiaDir = prefix </> "share" </> "aletheia"
                shareExists <- doesDirectoryExist shareAletheiaDir
                when shareExists $
                    liftIO $ removeDirectoryRecursive shareAletheiaDir
                putInfo ""
                putInfo "Aletheia uninstalled successfully."
                putInfo ""
            else do
                putInfo $ "No manifest found at " ++ manifestFile
                putInfo "Nothing to uninstall."
