// Code generated by "stringer -type=ByteOrder -linecomment -output=byteorder_string.go"; DO NOT EDIT.

package aletheia

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LittleEndian-0]
	_ = x[BigEndian-1]
}

const _ByteOrder_name = "little_endianbig_endian"

var _ByteOrder_index = [...]uint8{0, 13, 23}

func (i ByteOrder) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ByteOrder_index)-1 {
		return "ByteOrder(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ByteOrder_name[_ByteOrder_index[idx]:_ByteOrder_index[idx+1]]
}
