// Code generated by "stringer -type=DBCAttrScope -linecomment -output=dbcattrscope_string.go"; DO NOT EDIT.

package aletheia

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DBCAttrScopeNetwork-0]
	_ = x[DBCAttrScopeNode-1]
	_ = x[DBCAttrScopeMessage-2]
	_ = x[DBCAttrScopeSignal-3]
	_ = x[DBCAttrScopeEnvVar-4]
	_ = x[DBCAttrScopeNodeMsg-5]
	_ = x[DBCAttrScopeNodeSig-6]
}

const _DBCAttrScope_name = "BU_BO_SG_EV_BU_BO_REL_BU_SG_REL_"

var _DBCAttrScope_index = [...]uint8{0, 0, 3, 6, 9, 12, 22, 32}

func (i DBCAttrScope) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DBCAttrScope_index)-1 {
		return "DBCAttrScope(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DBCAttrScope_name[_DBCAttrScope_index[idx]:_DBCAttrScope_index[idx+1]]
}
