// Code generated by "stringer -type=DBCVarType -linecomment -output=dbcvartype_string.go"; DO NOT EDIT.

package aletheia

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DBCVarTypeInt-0]
	_ = x[DBCVarTypeFloat-1]
	_ = x[DBCVarTypeString-2]
}

const _DBCVarType_name = "intfloatstring"

var _DBCVarType_index = [...]uint8{0, 3, 8, 14}

func (i DBCVarType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_DBCVarType_index)-1 {
		return "DBCVarType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DBCVarType_name[_DBCVarType_index[idx]:_DBCVarType_index[idx+1]]
}
