// Code generated by "stringer -type=ErrorKind -linecomment -output=errorkind_string.go"; DO NOT EDIT.

package aletheia

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrProtocol-0]
	_ = x[ErrValidation-1]
	_ = x[ErrState-2]
	_ = x[ErrFFI-3]
}

const _ErrorKind_name = "protocolvalidationstateffi"

var _ErrorKind_index = [...]uint8{0, 8, 18, 23, 26}

func (i ErrorKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ErrorKind_index)-1 {
		return "ErrorKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorKind_name[_ErrorKind_index[idx]:_ErrorKind_index[idx+1]]
}
