// Code generated by "stringer -type=IssueSeverity -linecomment -output=issueseverity_string.go"; DO NOT EDIT.

package aletheia

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SeverityError-0]
	_ = x[SeverityWarning-1]
}

const _IssueSeverity_name = "errorwarning"

var _IssueSeverity_index = [...]uint8{0, 5, 12}

func (i IssueSeverity) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_IssueSeverity_index)-1 {
		return "IssueSeverity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IssueSeverity_name[_IssueSeverity_index[idx]:_IssueSeverity_index[idx+1]]
}
