// Code generated by "stringer -type=Verdict -linecomment -output=verdict_string.go"; DO NOT EDIT.

package aletheia

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Holds-0]
	_ = x[Fails-1]
	_ = x[Unresolved-2]
}

const _Verdict_name = "holdsfailsunresolved"

var _Verdict_index = [...]uint8{0, 5, 10, 20}

func (i Verdict) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Verdict_index)-1 {
		return "Verdict(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Verdict_name[_Verdict_index[idx]:_Verdict_index[idx+1]]
}
