"""FFI infrastructure for loading and initializing the Aletheia shared library."""

from __future__ import annotations

import ctypes
import json
import os
import threading
import warnings
from pathlib import Path

from ..protocols import is_str_dict
from ._types import ProtocolError


def parse_json_object(s: str) -> dict[str, object]:
    """Parse a JSON string that is expected to be an object.

    Wraps ``json.loads`` with validation and proper typing so
    callers get ``dict[str, object]`` instead of ``dict[Unknown, Unknown]``.
    """
    parsed: object = json.loads(s)
    if not is_str_dict(parsed):
        raise ProtocolError(f"Expected JSON object, got {type(parsed).__name__}")
    return parsed


class RTSState:
    """Module-level GHC RTS management.

    GHC RTS can only be initialized once per process.  We reference-count
    clients so ``hs_init()`` is called on first use and the RTS stays
    alive until process exit (GHC does not support reinitialization after
    ``hs_exit()``).
    """

    lib: ctypes.CDLL | None = None
    refcount: int = 0
    initialized: bool = False
    cores: int = 0
    _lock: threading.Lock = threading.Lock()

    @classmethod
    def acquire(cls, lib: ctypes.CDLL, rts_cores: int = 1) -> None:
        """Increment RTS reference count, initializing on first use.

        Args:
            lib: The loaded shared library.
            rts_cores: Number of GHC RTS capabilities (``-N`` flag).
                Use 1 (default) for single-bus monitoring.  Set to the
                number of CAN buses for multi-bus monitoring from
                separate Python threads.  Only takes effect on the first
                ``AletheiaClient`` created in a process.
        """
        with cls._lock:
            if not cls.initialized:
                lib.hs_init.argtypes = [
                    ctypes.POINTER(ctypes.c_int),
                    ctypes.POINTER(ctypes.POINTER(ctypes.c_char_p)),
                ]
                lib.hs_init.restype = None
                if rts_cores > 1:
                    args = [b"aletheia", b"+RTS",
                            b"-N" + str(rts_cores).encode(), b"-RTS"]
                else:
                    args = [b"aletheia"]
                argc = ctypes.c_int(len(args))
                argv = (ctypes.c_char_p * len(args))(*args)
                argv_ptr = ctypes.cast(argv, ctypes.POINTER(ctypes.c_char_p))
                lib.hs_init(ctypes.byref(argc), ctypes.byref(argv_ptr))
                cls.lib = lib
                cls.cores = rts_cores
                cls.initialized = True
            elif rts_cores != cls.cores:
                warnings.warn(
                    f"GHC RTS already initialized with {cls.cores} core(s); "
                    + f"ignoring rts_cores={rts_cores}. Set rts_cores on the "
                    + "first AletheiaClient created in the process.",
                    stacklevel=3,
                )
            cls.refcount += 1

    @classmethod
    def release(cls) -> None:
        """Decrement RTS reference count."""
        with cls._lock:
            if cls.refcount > 0:
                cls.refcount -= 1


def find_ffi_library() -> Path:
    """Locate the libaletheia-ffi.so shared library.

    Search order:
    1. ``ALETHEIA_LIB`` environment variable (explicit path)
    2. Install config (generated by 'cabal run shake -- install')
    3. build/libaletheia-ffi.so (project root)
    4. haskell-shim/dist-newstyle/**/libaletheia-ffi.so (Cabal build dir)

    Returns:
        Path to the shared library

    Raises:
        FileNotFoundError: If library not found
    """
    # Check ALETHEIA_LIB environment variable (Docker, custom deployments).
    env_path = os.environ.get("ALETHEIA_LIB")
    if env_path:
        p = Path(env_path)
        if p.exists():
            return p
        raise FileNotFoundError(
            f"ALETHEIA_LIB={env_path} does not exist"
        )

    # Check install config (generated by 'cabal run shake -- install').
    # Lazy import: _install_config.py is generated at install time and may not exist.
    try:
        from .. import _install_config  # pylint: disable=import-outside-toplevel
        if _install_config.LIBRARY_PATH.exists():
            return _install_config.LIBRARY_PATH
    except ImportError:
        pass

    module_dir = Path(__file__).parent
    repo_root = module_dir.parent.parent.parent

    # Check project build dir first
    build_path = repo_root / "build" / "libaletheia-ffi.so"
    if build_path.exists():
        return build_path

    # Search Cabal dist-newstyle
    cabal_dir = repo_root / "haskell-shim" / "dist-newstyle"
    if cabal_dir.exists():
        for so_file in cabal_dir.rglob("libaletheia-ffi.so"):
            return so_file

    raise FileNotFoundError(
        "libaletheia-ffi.so not found. Build with: " +
        "cabal run shake -- build"
    )
