#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2025 Nicolas Pelletier
# SPDX-License-Identifier: BSD-2-Clause
#
# Probes go/.gremlins.yaml.
# Claim: the stringer outputs are held out of the Go mutation surface, and it
# is this file that holds them out. Each carries the "Code generated by
# stringer; DO NOT EDIT" header, and a mutant in one measures the generator
# rather than the package. A dry run of gremlins from go/ lists no mutant in
# a file named *_string.go; the same dry run with the exclusion overridden
# from the environment, which gremlins reads ahead of the file, lists some,
# which is what shows the file is doing the holding. Non-zero exit: a
# generated file carries a mutant with the file in force, or none with it
# overridden. Exits 0 with a note when gremlins is not installed, the claim
# being untestable then.
set -u
cd "$(dirname "$0")/.." || exit 2
command -v gremlins > /dev/null || { echo "gremlins not installed, claim untestable"; exit 0; }
lib="$PWD/build/libaletheia-ffi.so"
[ -f "$lib" ] || exit 2
with=$(cd go && ALETHEIA_LIB="$lib" gremlins unleash --dry-run ./aletheia 2>&1) || {
    echo "the dry run did not run"; exit 1; }
# A pattern that matches no path, in the environment, overrides the file's.
without=$(cd go && GREMLINS_UNLEASH_EXCLUDE_FILES='^$' ALETHEIA_LIB="$lib" \
    gremlins unleash --dry-run ./aletheia 2>&1) || {
    echo "the dry run with the exclusion overridden did not run"; exit 1; }
status=0
held=$(printf '%s\n' "$with" | grep -c ' at [a-z_]*_string\.go')
free=$(printf '%s\n' "$without" | grep -c ' at [a-z_]*_string\.go')
[ "$held" -eq 0 ] || { echo "$held mutants listed in generated files with the file in force"; status=1; }
[ "$free" -gt 0 ] || { echo "no mutant listed in a generated file with the exclusion overridden, so the file holds nothing out"; status=1; }
[ "$status" -eq 0 ] && echo "PASS: the file holds $free mutants of the generated files out"
exit $status
