#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2025 Nicolas Pelletier
# SPDX-License-Identifier: BSD-2-Clause
#
# Probes Shakefile.hs, `extractFFIName` through the `check-ffi-names` phony.
# Claim: the FFI-name gate reads the mangled name from the wrapper's call,
# whatever punctuation surrounds it, and from nothing else. A call glued to
# an opening parenthesis reads as the same name as a bare one; a backticked
# mention of a wrong name in a `--` comment neither fails the gate nor
# satisfies it; a call carrying wrong digits fails it naming both names; a
# wrapper whose only spelling of the name is in a comment fails it. Each arm
# hands the phony a scratch copy of the shim's wrapper, rewritten into one
# shape, through ALETHEIA_FFI_WRAPPER; the digits come from the wrapper as it
# stands, so a renumbering does not age this probe. Non-zero exit: an arm
# that must pass fails, one that must fail passes, or a failure does not name
# its cause. Exits 2 when the MAlonzo tree is absent, which
# `cabal run shake -- build` writes.
set -u
cd "$(dirname "$0")/.." || exit 2
[ -f build/MAlonzo/Code/Aletheia/Main.hs ] || { echo "no MAlonzo tree: run cabal run shake -- build first"; exit 2; }
wrapper=haskell-shim/src/AletheiaFFI.hs
name=$(grep -o 'AgdaJSON\.d_processJSONLine_[0-9]*' "$wrapper" | head -n 1)
[ -n "$name" ] || { echo "$wrapper no longer calls AgdaJSON.d_processJSONLine_<digits>; rewrite the arms"; exit 2; }
digits=${name##*_}
wrong="AgdaJSON.d_processJSONLine_$((digits + 1))"
dir=$(mktemp -d) || exit 2
trap 'rm -rf "$dir"' EXIT
status=0

# Runs the phony on a wrapper and keeps its output; prints the exit status.
gate() {
    ALETHEIA_FFI_WRAPPER="$1" cabal run shake -- check-ffi-names > "$dir/out" 2>&1
    echo $?
}

# A bare invocation reads the shim's own wrapper, which is well-formed.
cabal run shake -- check-ffi-names > "$dir/out" 2>&1 || {
    echo "the phony fails on the shim's own wrapper with no path given"
    status=1
}

# Glued to an opening parenthesis, the call still reads as its name.
sed "s/$name/($name)/" "$wrapper" > "$dir/paren.hs"
grep -q "($name)" "$dir/paren.hs" || { echo "the paren arm did not rewrite the call"; exit 2; }
[ "$(gate "$dir/paren.hs")" -eq 0 ] || {
    echo "a call glued to an opening parenthesis fails the gate:"
    tail -n 5 "$dir/out"
    status=1
}

# A wrong name in a comment, before the call and again beside it, changes nothing.
awk -v call="$name" -v wrong="$wrong" '
    index($0, call) && !done { print "-- earlier this called `" wrong "`, see the log"; print $0 "  -- not `" wrong "`"; done = 1; next }
    { print }' "$wrapper" > "$dir/comment.hs"
[ "$(grep -c "$wrong" "$dir/comment.hs")" -eq 2 ] || { echo "the comment arm did not add its two mentions"; exit 2; }
[ "$(gate "$dir/comment.hs")" -eq 0 ] || {
    echo "a wrong name mentioned only in comments fails the gate:"
    tail -n 5 "$dir/out"
    status=1
}

# Wrong digits in the call fail the gate, and the failure names both names.
sed "s/$name/$wrong/" "$wrapper" > "$dir/wrong.hs"
grep -q "$wrong" "$dir/wrong.hs" || { echo "the wrong-digit arm did not rewrite the call"; exit 2; }
if [ "$(gate "$dir/wrong.hs")" -eq 0 ]; then
    echo "a call with wrong digits passes the gate"
    status=1
else
    grep -q 'MAlonzo function name mismatch for processJSONLine' "$dir/out" || { echo "the wrong-digit failure does not name the function"; status=1; }
    grep -q "Currently in FFI: *${wrong#AgdaJSON.}" "$dir/out" || { echo "the wrong-digit failure does not name the name it read"; status=1; }
    grep -q "Generated by Agda: *${name#AgdaJSON.}" "$dir/out" || { echo "the wrong-digit failure does not name the generated name"; status=1; }
    grep -q "sed -i .*$dir/wrong.hs" "$dir/out" || { echo "the fix hint names a file other than the one checked"; status=1; }
fi

# A wrapper that spells the name only in a comment has no call, and fails.
grep -v "$name" "$dir/comment.hs" > "$dir/nocall.hs"
grep -q "$wrong" "$dir/nocall.hs" || { echo "the no-call arm lost its comment mention"; exit 2; }
if [ "$(gate "$dir/nocall.hs")" -eq 0 ]; then
    echo "a wrapper that names the export only in a comment passes the gate"
    status=1
else
    grep -q "has no call to AgdaJSON.d_processJSONLine_" "$dir/out" || { echo "the no-call failure does not say the call is missing:"; tail -n 5 "$dir/out"; status=1; }
fi
exit $status
