{-# OPTIONS --safe --without-K #-}

-- Topology parsers for the DBC text format (Phase B.3.c.3) — facade
-- module.  The original monolithic implementation was split during
-- B.3.d ε.2 to break a cyclic module dependency:
--
--   Topology → Format → Properties.Primitives → Attributes → Topology
--
-- The cycle-relevant subset (CANID encoding + SG_ mux primitives) lives
-- in `Topology.Foundations`; the remaining BU_/SG_/BO_ machinery lives in
-- `Topology.SignalLine`.  This facade re-exports both halves so existing
-- importers continue to use `Aletheia.DBC.TextParser.Topology` unchanged.
--
-- Cycle-touching importers (`Properties.Primitives`, `Attributes`,
-- `Comments`, `Properties.Comments.Comment`,
-- `Properties.Attributes.Assign.{Message,Rel,Signal}`) import directly
-- from `Topology.Foundations` to avoid pulling in `SignalLine` (which,
-- post-ε.3, will import `Format.Receivers` and re-create the cycle).
--
-- Grammar slice covered (BNF section B from `Aletheia.DBC.TextParser`):
--   bu-section    ::= "BU_:" (ws identifier)* newline
--   message       ::= "BO_" ws nat ws identifier ws? ":" ws nat ws identifier
--                     newline signal*
--   signal        ::= " SG_" ws identifier mux-ind? ws? ":" ws? nat "|" nat
--                     "@" byte-order-digit sign ws? "(" rational "," rational
--                     ")" ws? "[" rational "|" rational "]" ws? string-lit
--                     ws? identifier ("," identifier)* newline
--   mux-ind       ::= ws "M" | ws "m" nat | ws "m" nat "M"
--
-- Two-stage design:
--   Stage 1 (`parseSignalLine` → `RawSignal`) — capture syntactic fields
--     including the raw mux marker (`M` / `m<N>` / `m<N>M`).  Cannot build a
--     `DBCSignal` yet because the `SignalPresence.When` constructor needs
--     the *name* of the parent master, which only becomes known after all
--     SG_ lines under a BO_ are collected.
--   Stage 2 (`resolveSignalList`) — scans the captured RawSignals for the
--     master via `findMuxName`, then rebuilds each one as `DBCSignal` with
--     the parent master's name wired into `When`.  A `SelBy`/`BothMux`
--     signal with no master found in the same BO_ block is an ill-formed
--     input and aborts the parse.
--
-- CANId encoding (cantools bit-31 flag convention): raw ≥ 2^31 decodes to
-- `Extended (raw − 2^31)`; raw < 2^31 decodes to `Standard raw` (must fit
-- in 11 bits).  Mirrored by `TextFormatter.Topology.rawCanIdℕ`.
--
-- Validation scope (B.3.c.3): range-checks on CAN ID, DLC byte count, and
-- mux reference resolution; the `physicalGate` predicate from
-- `JSONParser.parseSignalFields` is NOT applied at text-parse time — it is
-- a semantic-layer validator concern, and applying it here would couple
-- the parser to `ParseError` (out of scope for B.3.c.3, which stays on
-- `Maybe`-valued parsers throughout).
--
-- Deferred to later sub-commits:
--   * Multi-value mux selectors (`SG_MUL_VAL_`) — the syntactic drop
--     parser lands in B.3.c.8 (see `TextParser.ExtendedMux`); the
--     cross-line coordination that turns those parsed-and-dropped
--     ranges into actual multi-value `When` selectors is deferred to
--     a later mux-integration sub-commit.  Single-value `m<N>`
--     selectors map to a singleton `values = N List⁺.∷ []` today.
--   * BO_TX_BU_ `senders` — future sub-commit; for now `senders = []`.
--   * Integer-valued SG_ signals with `signalDef.startBit` physical-gate
--     rejection — leave to the validator per the scope note above.
module Aletheia.DBC.TextParser.Topology where

open import Aletheia.DBC.TextParser.Topology.Foundations public
open import Aletheia.DBC.TextParser.Topology.SignalLine public
