# SPDX-FileCopyrightText: 2025 Nicolas Pelletier
# SPDX-License-Identifier: BSD-2-Clause
"""The partition of the C++ mutation surface into the slices a CI job each sweeps.

The lane's sweep costs the runs of its mutants, and the lane splits that
across jobs by holding files out: a slice's Mull configuration is
``cpp/mull.yml`` with the files of every other slice added to ``excludePaths``,
so the slice's build carries its own files' mutants alone and the merge
unions the slices back into the lane's census.

Nothing here is a list anyone keeps.  The domain is every tracked file under
the library's source directories that the configuration does not already hold
out, so a file added to the library joins the partition the moment it is
tracked.  That the slices state what they exclude rather than what they
include is the same refusal read from the other side: a file no slice claims
is mutated by all of them, and the merge refuses the duplicated identifiers,
where a slice stating what it includes would drop that file's mutants and
report a smaller census as a clean sweep.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING, NewType, cast

import yaml

from tools._common import RelPath, git_ls_files

if TYPE_CHECKING:
    from collections.abc import Iterable, Mapping, Sequence
    from pathlib import Path

# Slices the lane is swept in.  Three, because at three the partition is
# within half a percent of even over the recorded weights, which the merge
# measures on every run by printing what the heaviest slice costs against an
# equal share, while the fixed cost each job pays before it sweeps (the
# toolchain, the library and the mutation build) is paid three times rather
# than more.  Whether three stays right is the scheduled review's question,
# answered from that print (docs/operations/MUTATION.md).
CPP_SLICES = 3

# Where the mutation build compiles the library from, and the benchmarks'
# directory, whose header the test binary instantiates.  A mutant's site is a
# file of one of these or of a path the configuration holds out; the merge is
# what holds that claim, by refusing a census that is not the recorded one.
CPP_SOURCE_TREES: tuple[str, ...] = ("cpp/src", "cpp/include", "cpp/benchmarks")

# Mutants a file carries, as a census counted them.
type MutantCounts = Mapping[RelPath, int]

# The work a file's mutants cost the lane's sweep, in runs of the unmutated
# suite (tools/mutation_cpp_runs.py), and the lane's figures by file.
SuiteRuns = NewType("SuiteRuns", float)
type FileRuns = dict[RelPath, SuiteRuns]

# What a partition balances: the lane's suite runs, or a count such as a file's size.
type SliceWeights = Mapping[RelPath, SuiteRuns] | MutantCounts

# One slice: the files whose mutants its build carries.
type Slice = tuple[RelPath, ...]

_GENERATED_HEADER = """\
# Generated by tools/mutation_cpp_slices.py; edits are overwritten.
# {what}: the mutation configuration of {config},
# {why}.
"""

_SLICE_WHY = """\
with the files of the other slices held out so this
# build carries this slice's mutants alone.  The merge unions the slices
# and refuses a census that is not the recorded one, which is what a file
# missing from every slice -- and so mutated by all of them, under identifiers
# that then arrive twice -- fails on"""


def _load_config(config_path: Path) -> dict[str, object]:
    """Read a Mull configuration as a mapping, refusing anything else with its path."""
    document = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    if not isinstance(document, dict):
        msg = f"{config_path} is not a Mull configuration: its top level is no mapping"
        raise TypeError(msg)
    return cast("dict[str, object]", document)


def held_out_patterns(config_path: Path) -> list[str]:
    """Read the path patterns the Mull configuration holds out of every sweep."""
    excludes = _load_config(config_path).get("excludePaths", [])
    return [str(pattern) for pattern in cast("list[object]", excludes)]


def hold_out_pattern(path: RelPath) -> str:
    """Build the Mull pattern matching one file and nothing else.

    Anchored at the leading separator and at the end, so a file's pattern
    cannot reach one whose name ends in it: anchored this way,
    ``cpp/src/backend.cpp`` does not match ``cpp/src/ffi_backend.cpp``.
    """
    return re.escape("/" + path) + "$"


def slice_domain(repo_root: Path, config_path: Path) -> list[RelPath]:
    """Every tracked file a slice can claim: the library's sources, less what the config holds out.

    Derived from the tree rather than listed, because a list is what a later
    file is forgotten from.  The patterns are matched against the path rooted
    at a separator, which is how the configuration's own patterns are written
    and how the plugin sees the absolute path of a mutant's site.
    """
    holdouts = [re.compile(pattern) for pattern in held_out_patterns(config_path)]
    return sorted(
        path
        for path in git_ls_files(repo_root, *CPP_SOURCE_TREES)
        if not any(holdout.search("/" + path) for holdout in holdouts)
    )


def partition(
    domain: Sequence[RelPath], weights: SliceWeights, slices: int = CPP_SLICES
) -> tuple[Slice, ...]:
    """Split the domain into slices of near-equal weight, the heaviest file placed first.

    A file weighs what the caller recorded of it: for the C++ lane, the suite
    runs its mutants cost when the weights were last taken, since a mutant's
    cost varies by file.  Most of the domain carries no mutant and the record
    does not name it, so an unnamed file weighs nothing, which is right for
    those and costs a new file only balance, never coverage.

    Longest-processing-time: each file in turn joins the lightest slice so
    far.  Ties break on the path and on the slice's own number, so one domain
    and one record give one partition whatever order the caller held them in,
    which is what lets every leg compute it apart and agree.
    """
    claimed: list[list[RelPath]] = [[] for _ in range(slices)]
    load = [0.0] * slices
    for path in sorted(domain, key=lambda path: (-weights.get(path, 0), path)):
        lightest = min(range(slices), key=lambda number: (load[number], number))
        claimed[lightest].append(path)
        load[lightest] += weights.get(path, 0)
    return tuple(tuple(sorted(files)) for files in claimed)


def slice_config_text(
    config_path: Path, held_out: Iterable[RelPath], number: int, total: int
) -> str:
    """One slice's Mull configuration, as text.

    The mutator set, the timeout and the hold-outs the configuration states
    stay where they are written; the slice adds the files it does not claim.
    Text rather than a file, because this content is what decides whether the
    build holding it is stale: nothing else in the build knows an object
    depends on it.
    """
    return _config_text(config_path, held_out, f"Slice {number} of {total}", _SLICE_WHY)


def _config_text(config_path: Path, held_out: Iterable[RelPath], what: str, why: str) -> str:
    """One generated Mull configuration: the lane's, narrowed by files."""
    config = _load_config(config_path)
    excludes = held_out_patterns(config_path)
    config["excludePaths"] = excludes + [hold_out_pattern(path) for path in held_out]
    header = _GENERATED_HEADER.format(what=what, config=config_path.name, why=why)
    return header + yaml.safe_dump(config, sort_keys=False)
