# SPDX-FileCopyrightText: 2025 Nicolas Pelletier
# SPDX-License-Identifier: BSD-2-Clause
"""The partition of the C++ mutation surface into the slices a CI job each sweeps.

A tree's sweep costs its runner's wall clock times its mutants, and the lane
splits that across jobs by holding files out: a slice's Mull configuration is
the tree's own with the files of every other slice added to ``excludePaths``,
so the slice's build carries its own files' mutants alone and the merge
unions the slices back into the tree's census.

Nothing here is a list anyone keeps.  The domain is every tracked file under
the library's source directories that the configuration does not already hold
out, so a file added to the library joins the partition the moment it is
tracked.  That the slices state what they exclude rather than what they
include is the same refusal read from the other side: a file no slice claims
is mutated by all of them, and the merge refuses the duplicated identifiers,
where a slice stating what it includes would drop that file's mutants and
report a smaller census as a clean sweep.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING, cast

import yaml

from tools._common import RelPath, git_ls_files

if TYPE_CHECKING:
    from collections.abc import Iterable, Mapping, Sequence
    from pathlib import Path

# Slices one mutation tree is swept in.  Three, because the partition is even
# at three over the recorded census, which the merge measures on every run by
# printing what the heaviest slice carries against an equal share, while the
# fixed cost each job pays before it sweeps -- the toolchain, the library and
# the tree's build -- is paid three times per tree rather than more.  Whether
# three stays right is the scheduled review's question, answered from the
# per-mutant durations a run's reports carry rather than from any run's
# print (docs/operations/MUTATION.md).
CPP_SLICES = 3

# Where the mutation build compiles the library from.  A mutant's site is a
# file of one of these or of a path the configuration holds out; the merge is
# what holds that claim, by refusing a census that is not the recorded one.
CPP_SOURCE_TREES: tuple[str, ...] = ("cpp/src", "cpp/include")

# Mutants a file carries, as a census counted them.
type MutantCounts = Mapping[RelPath, int]

# One slice: the files whose mutants its build carries.
type Slice = tuple[RelPath, ...]

_GENERATED_HEADER = """\
# Generated by tools/mutation_cpp_slices.py; edits are overwritten.
# {what}: the mutation configuration of {config},
# {why}.
"""

_SLICE_WHY = """\
with the files of the other slices held out so this
# build carries this slice's mutants alone.  The merge unions a tree's slices
# and refuses a census that is not the recorded one, which is what a file
# missing from every slice -- and so mutated by all of them, under identifiers
# that then arrive twice -- fails on"""

_DROPPED_WHY = """\
without the mutators listed below, which this tree
# cannot read: a sanitizer that instruments the program inserts its own calls
# at the source location of the statement they guard, so a mutator over calls
# mutates the sanitizer's checks rather than the program's, and removing a
# check changes nothing any test can observe"""


def _load_config(config_path: Path) -> dict[str, object]:
    """Read a Mull configuration as a mapping, refusing anything else with its path."""
    document = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    if not isinstance(document, dict):
        msg = f"{config_path} is not a Mull configuration: its top level is no mapping"
        raise TypeError(msg)
    return cast("dict[str, object]", document)


def held_out_patterns(config_path: Path) -> list[str]:
    """Read the path patterns the Mull configuration holds out of every sweep."""
    excludes = _load_config(config_path).get("excludePaths", [])
    return [str(pattern) for pattern in cast("list[object]", excludes)]


def hold_out_pattern(path: RelPath) -> str:
    """Build the Mull pattern matching one file and nothing else.

    Anchored at the leading separator and at the end, so a file's pattern
    cannot reach one whose name ends in it: anchored this way,
    ``cpp/src/backend.cpp`` does not match ``cpp/src/ffi_backend.cpp``.
    """
    return re.escape("/" + path) + "$"


def slice_domain(repo_root: Path, config_path: Path) -> list[RelPath]:
    """Every tracked file a slice can claim: the library's sources, less what the config holds out.

    Derived from the tree rather than listed, because a list is what a later
    file is forgotten from.  The patterns are matched against the path rooted
    at a separator, which is how the configuration's own patterns are written
    and how the plugin sees the absolute path of a mutant's site.
    """
    holdouts = [re.compile(pattern) for pattern in held_out_patterns(config_path)]
    return sorted(
        path
        for path in git_ls_files(repo_root, *CPP_SOURCE_TREES)
        if not any(holdout.search("/" + path) for holdout in holdouts)
    )


def partition(
    domain: Sequence[RelPath], weights: MutantCounts, slices: int = CPP_SLICES
) -> tuple[Slice, ...]:
    """Split the domain into slices of near-equal sweep cost, the heaviest file placed first.

    A file weighs the mutants the recorded census counts in it, which stands
    for its share of the sweep because the cost of a mutant hardly varies:
    over the recorded run it was 4.6 seconds, and the files that depart from
    it are the ones carrying a handful of mutants.  Most of the domain carries
    none and the census does not name it, so an unnamed file weighs nothing,
    which is right for those and costs a new file only balance, never
    coverage: the run that adds a file re-takes the census in the same commit,
    because the merge refuses a union whose total is not the recorded one.

    Longest-processing-time: each file in turn joins the lightest slice so
    far.  Ties break on the path and on the slice's own number, so one domain
    and one census give one partition whatever order the caller held them in,
    which is what lets six jobs compute it apart and agree.
    """
    claimed: list[list[RelPath]] = [[] for _ in range(slices)]
    load = [0] * slices
    for path in sorted(domain, key=lambda path: (-weights.get(path, 0), path)):
        lightest = min(range(slices), key=lambda number: (load[number], number))
        claimed[lightest].append(path)
        load[lightest] += weights.get(path, 0)
    return tuple(tuple(sorted(files)) for files in claimed)


def slice_config_text(
    config_path: Path,
    held_out: Iterable[RelPath],
    number: int,
    total: int,
    dropped_mutators: Sequence[str] = (),
) -> str:
    """One slice's Mull configuration, as text.

    The mutator set, the timeout and the hold-outs the tree states stay where
    they are written; the slice adds the files it does not claim, and a tree
    that cannot read a mutator drops it.  Text rather than a file, because this
    content is what decides whether the tree holding it is stale: nothing else
    in the build knows an object depends on it.
    """
    what = f"Slice {number} of {total}"
    why = _SLICE_WHY if not dropped_mutators else f"{_SLICE_WHY}, and {_DROPPED_WHY}"
    return _config_text(config_path, held_out, dropped_mutators, what, why)


def tree_config_text(config_path: Path, dropped_mutators: Sequence[str]) -> str:
    """Build a whole tree's configuration, as text, without the mutators it cannot read."""
    return _config_text(config_path, (), dropped_mutators, "Whole tree", _DROPPED_WHY)


def _config_text(
    config_path: Path,
    held_out: Iterable[RelPath],
    dropped_mutators: Sequence[str],
    what: str,
    why: str,
) -> str:
    """One generated Mull configuration: the tree's, narrowed by files and by mutators."""
    config = _load_config(config_path)
    excludes = held_out_patterns(config_path)
    config["excludePaths"] = excludes + [hold_out_pattern(path) for path in held_out]
    mutators = cast("list[str]", config.get("mutators", []))
    config["mutators"] = [name for name in mutators if name not in set(dropped_mutators)]
    header = _GENERATED_HEADER.format(what=what, config=config_path.name, why=why)
    return header + yaml.safe_dump(config, sort_keys=False)
